### ISSUE TITLE
Memory leak with time limits

### ISSUE THREAD

**Issue by cyounkins** [celery/celery#1129]
amqp==1.0.6
billiard==2.7.3.19 and 2.7.3.18
celery==3.0.12
kombu==2.5.4

CELERY_IMPORTS = (...)
CELERY_SEND_EVENTS = True
CELERY_TASK_PUBLISH_RETRY = True
CELERY_SEND_TASK_ERROR_EMAILS = True
CELERY_RESULT_PERSISTENT = True
CELERY_STORE_ERRORS_EVEN_IF_IGNORED = True
CELERY_RESULT_BACKEND = "mongodb"
CELERY_EAGER_PROPAGATES_EXCEPTIONS = True
CELERY_ACKS_LATE = True

CELERYD_POOL = 'processes'
CELERYD_CONCURRENCY = 5
CELERYD_TASK_SOFT_TIME_LIMIT = 60 \* 60 \* 12
CELERYD_TASK_TIME_LIMIT = 60 \* 60 \* 13
CELERYD_LOG_FILE = os.path.join(LOG_DIR, 'celery.log')

BROKER_HEARTBEAT = 30
BROKER_CONNECTION_RETRY = True
BROKER_CONNECTION_MAX_RETRIES = 100
BROKER_CONNECTION_TIMEOUT = 4

CELERY_MONGODB_BACKEND_SETTINGS = {
    'host': MONGODB_HOSTNAME,
}
CELERYD_LOG_LEVEL = 'DEBUG'
BROKER_URL = "pyamqp://blahblah"

---

Switched from using gevent to the processes pool, now the main process (the first of the 6, not one of the workers) consumes memory monotonically, eventually invoking the kernel's OOM killer.
1. What could be causing this issue, and how can I better diagnose it?
2. Bugs like this seem to happen a lot to me, and it's getting frustrating. Can I add memory monitoring / debug output for every N tasks? Would this be accepted in a pull request?

**Comment by jakubczaplicki** [comment]
What version has this bug been fixed in ?
I am seeing a memory leak in celery==3.1.23. Although I don't use any CELERYD_* settings.

**Comment by shachr** [comment]
@ask we're experiencing SystemExit and we think its related to the memory leak, we do use CELERYD_TASK_TIME_LIMIT and  CELERYD_TASK_SOFT_TIME_LIMIT limits, it is still an ongoing issue ? we're using `celery[librabbitmq]==3.1.19`

thanks!

**Comment by sivang** [comment]
still experiencing this with latest checked out master branch form github

**Comment by thedrow** [comment]
Please open a new issue about the problem you are having.
It is likely completely different from the OPs problem.

**Comment by glazari** [comment]
It seams I am having this issue in 2018 with `celery==4.2.1`.

I have tried many different things to solve my memory leak, including what was suggested by https://github.com/celery/celery/pull/4839

But what finally seems to have solved my problem was to remove the `--time-limit` from the cli command.

Is anyone looking in to this? should I open a new issue?

**Comment by auvipy** [comment]
please open a new issue referencing this one and related ones
