### ISSUE TITLE
Revoking completed tasks causes the worker to stop consuming tasks

### ISSUE THREAD

**Issue by thedrow** [celery/celery#2620]
I have no idea why but I am getting these logs from celery worker for tasks scheduled by celery beat.

```
[2015-05-14 11:17:22,062: INFO/MainProcess] Tasks flagged as revoked: 93bfa6f4-dbba-45b9-a830-8a952b5a595d
[2015-05-14 11:25:13,619: DEBUG/MainProcess] pidbox received method revoke(signal=u'SIGTERM', terminate=False, task_id=u'2b2ed497-5d26-40f1-a0f4-e7f4bd77ad4b') [reply_to:None ticket:None]
[2015-05-14 11:25:13,619: INFO/MainProcess] Tasks flagged as revoked: 2b2ed497-5d26-40f1-a0f4-e7f4bd77ad4b
[2015-05-14 11:26:02,463: DEBUG/MainProcess] pidbox received method revoke(signal=u'SIGTERM', terminate=False, task_id=u'66a6fd85-9da9-48c4-bcad-057a154c993b') [reply_to:None ticket:None]
[2015-05-14 11:26:02,463: INFO/MainProcess] Tasks flagged as revoked: 66a6fd85-9da9-48c4-bcad-057a154c993b
[2015-05-14 11:43:39,375: DEBUG/MainProcess] pidbox received method revoke(signal=u'SIGTERM', terminate=False, task_id=u'fa4ddf41-dc43-46ff-aa3a-4acbcbf4da40') [reply_to:None ticket:None]
[2015-05-14 11:43:39,375: INFO/MainProcess] Tasks flagged as revoked: fa4ddf41-dc43-46ff-aa3a-4acbcbf4da40
[2015-05-14 11:48:24,092: DEBUG/MainProcess] pidbox received method revoke(signal=u'SIGTERM', terminate=False, task_id=u'57cebaa8-2881-4da1-b1b0-1d12357155a9') [reply_to:None ticket:None]
```

After deleting the queues used by these tasks they start executing again.
Who issued a SIGTERM exactly?

**Comment by PMickael** [comment]
It's seem to come from a revoke usage, did you call revoke or revoke_selection ?

**Comment by thedrow** [comment]
After some detective work here is what's going on:
We are revoking tasks but we have a bug where we might revoke a task that is already completed.
This situation causes celery to stop consuming tasks.
We see that celery beat is publishing tasks but the worker isn't consuming them.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by ask** [comment]
This may be already fixed btw, since I already fixed an hanging+revoke bug. Sorry for closing your issue @thedrow. :)  We need to get these issues out of the way, and at current rate we will never be able to fix them.

**Comment by samonderous** [comment]
I'm seeing something very similar. We have a celery + redis setup and we're noticing celery die right after main process does a revoke. The last task in our logs is a revoke() before celery dies. Not 100% but @ask , what version was this fixed in?

**Comment by ask** [comment]
@samonderous Try 4.0rc  (pip install --pre celery)

**Comment by DylanYoung** [comment]
FYI: I'm still seeing this or something like in on Celery 4.2.  Problem is, I don't know where the revokes are coming from (does celery use revokes internally?).

**Comment by auvipy** [comment]
please try celery 4.3/4.4.0rc3/master and report again @DylanYoung

**Comment by DylanYoung** [comment]
Will try again with 4.3.0 when we're able to upgrade and give a detailed report.  Here are some notes for others encountering this issue:

First off: we *were* using revoke (not sure how I missed it before, oops)

1) We had a bug where we were issuing `revoke` on an empty string.  Removing this bug so far has greatly helped with the issue, though we don't think it has 100% fixed it (will update as we continue monitoring).  This indicates to me that there is still some kind of bug in celery 4.2.2 regarding revoke handling in workers (we're using redis transport and gevent workers).

If we can confirm that this fix isn't enough (get more freezing patterns), I'm going to try and put a guard in place to avoid running `revoke` on completed tasks. 

This is what the strace looks like after the workers start hanging FYI (though interestingly, they seem to stop logging before they freeze completely):

```
epoll_wait(15, [], 64, 59743)           = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=3700670, tv_nsec=145117900}) = 0
getpid()                                = 27997
clock_gettime(CLOCK_MONOTONIC, {tv_sec=3700670, tv_nsec=145420801}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=3700670, tv_nsec=145528301}) = 0
epoll_wait(15, [], 64, 59743)           = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=3700729, tv_nsec=947579410}) = 0
getpid()                                = 27997
clock_gettime(CLOCK_MONOTONIC, {tv_sec=3700729, tv_nsec=947665411}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=3700729, tv_nsec=947713611}) = 0
epoll_wait(15, 
```

**Comment by DylanYoung** [comment]
On that note, does anyone have a suggested best way to check whether a task has completed?

**Comment by thedrow** [comment]
It sounds like a bug to me.

**Comment by theardalanrazavi** [comment]
Hello, is there any update on this issue? we are seeing this issue with `celery==4.2.2` when trying to revoke tasks

**Comment by auvipy** [comment]
> Hello, is there any update on this issue? we are seeing this issue with `celery==4.2.2` when trying to revoke tasks

you should try 4.4.x or 5.x versions & report again
