### ISSUE TITLE
Task on_retry handler not called when retry raised in on_success handler

### ISSUE THREAD

**Issue by mjmonroe** [celery/celery#3528]
**Issue:**
I am using the on_success handler and on_failure task handlers to update a database. If I can not update the database for some reason, I retry the task. When self.retry is raised from the on_success handler, the on_retry handler is not called. When using an apply_async task, the on_failure handler is called instead with an exc of:

>  Retry in 10s: ValueError('Fake Exception',)

. When using apply to call a task, the on_success handler is called multiple times until the max_retry limit is reached.

```
# Example on_success handler
    def on_success(self, retval, task_id, args, kwargs):
        try:
            print(getattr(self.request, 'id', 'MISSING'))
            raise ValueError('Fake Exception')
        except Exception as exc:
            raise self.retry(exc=exc)
```

**Expected:**
I would expect that calling a retry from within on_success would result in the on_retry handler being called, both when calling a task with apply or apply_async. At a minimum, I would think that apply and apply_async should behave the same way.

**Versions with the issue:**
Celery 4.0.0rc6, Kombu 4.0.0rc6
Celery 4.0.0rc3, Kombu 4.0.0rc3

**Comment by mjmonroe** [comment]
It looks like you can [replace this](https://github.com/celery/celery/blob/b45c15dcb12d29d7d3f7357dfe3e5dd84a930efe/celery/app/trace.py#L471-L476) with the below to get apply_async tasks to work when on_success errors. The original code does two things incorrectly: 1) it assume that on_success will not retry, 2) it does not push the request back onto the stack which means that the on_failure handler does not get access to the original request object, it gets an empty one.
```
        except Retry as exc:
            if task_request is not None:
                push_task(task)
                push_request(task_request)
                I, R, state, retval = on_error(
                    task_request, exc, uuid, RETRY, call_errbacks=False)
        except Exception as exc:
            if eager:
                raise
            R = report_internal_error(task, exc)
            if task_request is not None:
                push_task(task)
                push_request(task_request)
                I, R, state, retval = on_error(task_request, exc, uuid)
```

**Comment by ask** [comment]
Yeah, on_success, on_failure, on_retry and the task related signal handlers cannot call .retry.

How it works is that it,

1) Executes the task function
2) Checks the return value, or exception raised by the task
3) Updates the result of the task depending on what the task returned.
4) Call handlers like Task.on_success,  signals.task_postrun etc.

This means on_success shouldn't call .retry, as the result state of the task has already been updated
to be SUCCESS, and cannot be set back to RETRY.

You can accomplish what you want here with a decorator though:

```py

from functools import wraps

def always_retry_on_success(fun):
    @wraps(fun)
    def _inner(self, *args, **kwargs):
         result = fun(self, *args, **kwargs)
         try:
             raise Exception('fake exception')
         except Exception:
             raise self.retry(exc=exc)
    return _inner


@task(bind=True)   # <-- need bind so the decorator has self argument.
@always_retry_on_success
def add(self, x, y):
    return x + y
```

**Comment by Novitoll** [comment]
Not sure if this issue is still relevant, but on `celery==4.1.0`, I'm still having problems to update the state to RETRY on retry method. Using the code below, on retry it shows "FAILURE" status instead of "PENDING"

```python
class BaseTask(celery_instance.Task):
    abstract = True

    def backoff(self, retry_attempts):
        return 2 ** retry_attempts if retry_attempts <= 5 else 0

    def retry(self, exc=None, **options):
        self.update_state(state=states.RETRY, meta={'message': exc.message})
        super(BaseTask, self).retry(countdown=self.backoff(self.request.retries), exc=exc, **options)

    def on_retry(self, exc, task_id, args, kwargs, einfo):
        self.update_state(state=states.RETRY, meta={'message': exc.message})
        super(BaseTask, self).on_retry(exc, task_id, args, kwargs, einfo)

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        self.update_state(state=states.FAILURE, meta={'message': exc.message})
        super(BaseTask, self).on_failure(exc, task_id, args, kwargs, einfo)


@celery_instance.task(bind=True, base=BaseTask)
def fun(self):
    try:
       # do your task
    except Exception as exc:
      self.retry(exc=exc)
```

**Comment by auvipy** [comment]
this should be fixed on latest master please check and report if not

**Comment by carlossantos-mb** [comment]
It's still a problem, when retry to second time don't send the headers.
