### ISSUE TITLE
Subsequent groups within a chain fail

### ISSUE THREAD

**Issue by mheppner** [celery/celery#3585]
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.10
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:FreeBSD arch:64bit, ELF imp:PyPy
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:cache+memcached://10.1.1.2:11211/
```
```
amqp==2.1.1
celery==4.0.0
Django==1.10.3
librabbitmq==1.6.1
pylibmc==1.5.1
```

## Steps to reproduce

```python
# celery.py
from __future__ import absolute_import
import os
from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')

app = Celery('project')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks(force=True)
```

```python
from celery import task, group, chain

@task
def add(x, y):
    return x + y

# chain( task, group(tasks) )
x = chain( add.si(1, 1), group([add.si(1, 1), add.si(1, 1)]) )
type(x) # celery.canvas._chain
x.apply_async() # works as expected

# chain( task, group(tasks), group(tasks) )
x = chain( add.si(1, 1), group([add.si(1, 1), add.si(1, 1)]), group([add.si(1, 1), add.si(1, 1)]) )
type(x) # celery.canvas._chain
x.apply_async() # fails, traceback below

# chain( task, group(tasks), task, group(tasks) )
x = chain( add.si(1, 1), group([add.si(1, 1), add.si(1, 1)]), add.si(1, 1), group([add.si(1, 1), add.si(1, 1)]) )
type(x) # celery.canvas._chain
x.apply_async() # works as expected
```

## Expected behavior

It seems like a chain containing subsequent groups fails. If there is a task in between, or just a single group, it works as expected. This is different behavior from 3.x and I can't seem to find any obvious differences in the docs. The only thing that looks relevant in the release notes is the fix about `group | group` being flattened into a single group (#2573).

## Actual behavior

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-30-495e2ee230ea> in <module>()
----> 1 x.apply_async()

/project/site-packages/celery/canvas.pyc in delay(self, *partial_args, **partial_kwargs)
    180     def delay(self, *partial_args, **partial_kwargs):
    181         """Shortcut to :meth:`apply_async` using star arguments."""
--> 182         return self.apply_async(partial_args, partial_kwargs)
    183 
    184     def apply(self, args=(), kwargs={}, **options):

/project/site-packages/celery/canvas.pyc in apply_async(self, args, kwargs, **options)
    565             return self.apply(args, kwargs, **options)
    566         return self.run(args, kwargs, app=app, **(
--> 567             dict(self.options, **options) if options else self.options))
    568 
    569     def run(self, args=(), kwargs={}, group_id=None, chord=None,

/project/site-packages/celery/canvas.pyc in run(self, args, kwargs, group_id, chord, task_id, link, link_error, publisher, producer, root_id, parent_id, app, **options)
    584             tasks, results = self.prepare_steps(
    585                 args, self.tasks, root_id, parent_id, link_error, app,
--> 586                 task_id, group_id, chord,
    587             )
    588 

/project/site-packages/celery/canvas.pyc in prepare_steps(self, args, tasks, root_id, parent_id, link_error, app, last_task_id, group_id, chord_body, clone, from_dict)
    663                 task = chord(
    664                     task, body=prev_task,
--> 665                     task_id=prev_res.task_id, root_id=root_id, app=app,
    666                 )
    667 

AttributeError: 'GroupResult' object has no attribute 'task_id'
```

**Comment by xavierp** [comment]
Hey there. Look's like i'm facing the same issue.
Any workaround ?

I'm working with :
```
amqp (2.1.4)
celery (4.0.2)
kombu (4.0.2)
```

Here is my stack trace:
```python
Apr  4 19:31:59: File ".python/3.5-dev/lib/python3.5/site-packages/celery/canvas.py", line 567, in apply_async
Apr  4 19:31:59: dict(self.options, **options) if options else self.options))
Apr  4 19:31:59: File ".python/3.5-dev/lib/python3.5/site-packages/celery/canvas.py", line 586, in run
Apr  4 19:31:59: task_id, group_id, chord,
Apr  4 19:31:59: File ".python/3.5-dev/lib/python3.5/site-packages/celery/canvas.py", line 665, in prepare_steps
Apr  4 19:31:59: task_id=prev_res.task_id, root_id=root_id, app=app,
Apr  4 19:31:59: AttributeError: 'GroupResult' object has no attribute 'task_id'
```


My workflow looks like:
(TaskA | Group B | Group C | Goup D | Task E) and all the tasks are immutable.
RabbitMQ is used as broker and Mysql as result backend.

Regards.

**Comment by mheppner** [comment]
It's not that ideal, but you can throw an empty/dummy task in between.

**Comment by xavierp** [comment]
@mheppner 
Yes i could do that but it is far from ideal...

I'll wait and hope for a bugfix.
I would be glad to do it but but i'm not familiar enough with Celery internals :/

**Comment by yoichi** [comment]
> It's not that ideal, but you can throw an empty/dummy task in between.

It does avoid error, but it ends up with wrong exection.

It seems that the behavior with multiple groups in chain seems to be broken in Celery v4.
Following example illustrate it:

```
# myapp.py (run worker with: celery -A myapp worker)
from celery import Celery

app = Celery('tasks', backend='redis://localhost:6379', broker='redis://localhost:6379')

@app.task
def nop(*args):
    print(args)
```

```
# myapp_run.py
import celery
import myapp

celery.chain(myapp.nop.si("1"),
             celery.group(myapp.nop.si("2-a"), myapp.nop.si("2-b")),
             myapp.nop.si("3"),
             celery.group(myapp.nop.si("4-a"), myapp.nop.si("4-b")),
             myapp.nop.si("5")).delay().get()
```

worker output with Celery v3.1.25 (expected behavior)

```
[2017-05-01 10:44:46,159: WARNING/Worker-2] ('1',)
[2017-05-01 10:44:46,178: WARNING/Worker-1] ('2-a',)
[2017-05-01 10:44:46,188: WARNING/Worker-2] ('2-b',)
[2017-05-01 10:44:46,693: WARNING/Worker-1] ('3',)
[2017-05-01 10:44:46,708: WARNING/Worker-2] ('4-a',)
[2017-05-01 10:44:46,712: WARNING/Worker-1] ('4-b',)
[2017-05-01 10:44:47,217: WARNING/Worker-2] ('5',)
```

worker output with Celery v4.0.2 (unexpected behavior)

```
[2017-05-01 10:42:41,983: WARNING/PoolWorker-2] ('1',)
[2017-05-01 10:42:41,986: WARNING/PoolWorker-1] ('2-a',)
[2017-05-01 10:42:41,988: WARNING/PoolWorker-2] ('2-b',)
[2017-05-01 10:42:41,990: WARNING/PoolWorker-1] ('4-a',)
[2017-05-01 10:42:41,992: WARNING/PoolWorker-1] ('4-b',)
[2017-05-01 10:42:41,995: WARNING/PoolWorker-1] ('4-b',)
[2017-05-01 10:42:41,995: WARNING/PoolWorker-2] ('4-a',)
[2017-05-01 10:42:42,000: WARNING/PoolWorker-1] ('3',)
[2017-05-01 10:42:42,013: WARNING/PoolWorker-1] ('5',)
[2017-05-01 10:42:42,013: WARNING/PoolWorker-2] ('5',)
[2017-05-01 10:42:42,014: WARNING/PoolWorker-2] ('4-a',)
[2017-05-01 10:42:42,016: WARNING/PoolWorker-2] ('4-b',)
[2017-05-01 10:42:42,018: WARNING/PoolWorker-2] ('5',)
```

Tested with:

* OS: Ubuntu 16.04.1
* Python: 3.5.2
* Redis: 3.0.6

**Comment by georgepsarakis** [comment]
@yoichi I think the issue you are describing is fixed in `master`. @xavierp is it possible to give example tasks and a chain that reproduce the issue? Thanks.

**Comment by yoichi** [comment]
@georgepsarakis Thanks for the information. I've confirmed the problem is not reproduced with master.

**Comment by denhartog** [comment]
chained groups are still broken; using a "placeholder task" bypasses error of:
AttributeError: 'GroupResult' object has no attribute 'task_id'

**Comment by drhagen** [comment]
I can confirm that this group-following-group error still occurs on 4.1.0. I don't know when 4.1.0 diverged from master, but it was released it a couple months after @georgepsarakis and @yoichi tested master. Strangely, if one of the groups happens to have only one element, then the error does not occur, so there must actually be multiple signatures per group to reliably test for the bug.

**Comment by denniswalker** [comment]
+1 - Just encountered it as well.

**Comment by auvipy** [comment]
could you try celery 4.2?

**Comment by denniswalker** [comment]
Updated to 4.2.1 and am still receive "AttributeError: 'GroupResult' object has no attribute 'task_id'" for two consecutive groups in a chain.

**Comment by denniswalker** [comment]
Doing this in the meantime:

**Comment by illagrenan** [comment]
Thanks @denniswalker for this workaround. Group separator worked for me as I commented here: https://github.com/celery/celery/issues/4848#issuecomment-447317343.
