### ISSUE TITLE
Unacked messages return to queue shortly after soft shutdown (RabbitMQ)

### ISSUE THREAD

**Issue by KBoehme** [celery/celery#3653]
## Checklist
```
pip list | grep celery
celery (4.0.0) #Tested on master and seems its affected by this too.
```

## Steps to reproduce

1. Start a worker
2. Submit long running task where `acks_late=True` to worker.
3. Soft kill worker, the task continues to be processed as expected.
4. Wait ~35 seconds and see the same currently running task message resubmitted to queue.

```python
#Define a task where acks_late=True
@app.task(acks_late=True)
def sleep_task_1(time_to_sleep=60):
    logger.info('Running sleep_task_1! sleeping for {} seconds'.format(
        time_to_sleep))
    for i in range(time_to_sleep):
        print(i)
        sleep(1)

#Submit task
sleep.apply_async(kwargs={'time_to_sleep': 5000}) # Send long-running, acks_late=True task to running worker.
```

## Expected behavior
When a worker running a long running task configured with `acks_late=True` is soft killed it should continue to process the current task and SHOULD NOT resubmit the task message to the queue.

## Actual behavior
When a worker running a long running task configured with `acks_late=True` is soft killed it DOES continue to process the current task BUT resubmits the task message back to the queue shortly after getting soft killed.

**Comment by mjmonroe** [comment]
It looks like you can use [app.control.cancel_consumer](http://docs.celeryproject.org/en/latest/_modules/celery/app/control.html#Control.cancel_consumer) and pass in the worker's queue you want to stop consuming from. The worker will disconnect from the queue, but will not ack the message until after it has finished.

If that is the only queue you are consuming from, the worker will just stay running and not consume from any queues. You can now kill the worker at your leisure. I am using a bootstep timer which watches for a file. When it is present, and the worker is doing nothing, kill the node.


```
from pathlib import Path
from threading import Event
from celery import bootsteps
from celery.exceptions import WorkerTerminate, WorkerShutdown

from celery.utils.log import get_logger

logger = get_logger(__name__)

class TerminateFileMonitor(bootsteps.StartStopStep):
    requires = {'celery.worker.components:Hub'}
    # How often to check for kill file in seconds
    HEARTBEAT = 5
    k_file = '/run/lock/NUKEDABOX'
    exit_event = Event()

    def __init__(self, worker, **kwargs):
        self.tref = None
        self.count = 0

    def start(self, worker):
        self.tref = worker.hub.call_repeatedly(self.HEARTBEAT, self.detect, worker)

    def stop(self, worker):
        if self.tref:
            self.tref.cancel()
            self.tref = None

    def detect(self, worker):
        if self.terminate_file_present():
            logger.info('Terminate file {} present'.format(self.k_file))
            if len(worker.state.active_requests.data) == 0:
                logger.info('No active tasks, terminating celery')
                self.die()

    @staticmethod
    def die():
        raise WorkerTerminate()

    @staticmethod
    def terminate_file_present():
        return Path(TerminateFileMonitor.k_file).exists()

app.steps['worker'].add(TerminateFileMonitor)
```

**Comment by dejlek** [comment]
This is happening with Redis as a broker too (4.0.2) and it drives me nuts!! :(
I can't wait for this bug to be fixed!

**Comment by auvipy** [comment]
is the bug fixed in newer release or master?

**Comment by KBoehme** [comment]
Just tried again from master branch (pip version: celery (4.1.0)) and still see same behavior. A task that successfully finished after warm/soft/cozy/graceful shutdown gets requeued. And according to the comment above, this happens with other brokers as well.

**Comment by auvipy** [comment]
lets wait and see how it behave after 4.2 release. will look into it after 4.2 release this month

**Comment by slavab89** [comment]
Seems to still happen on 4.2.1.
Previously (on 4.1), once a shutdown started it would return the task to the queue without even waiting for it to finish.
Now on 4.2.1 it does wait for the task to finish before returning it to the queue.

**Comment by auvipy** [comment]
@slavab89 care to send a pr?

**Comment by slavab89** [comment]
Unfortunately i'm not sure what the actual fix should be, or where.
The workaround that i've suggested is something that could be dont on the application level outside the scope of Celery and this library.
