### ISSUE TITLE
chord on_error callback does not work as documented

### ISSUE THREAD

**Issue by NickStefan** [celery/celery#3709]
## Checklist

- version 4.0.2 of celery
- im just copying the examples from the docs from here: http://docs.celeryproject.org/en/latest/userguide/canvas.html#error-handling

## Steps to reproduce

file1.py
```
from celery import chord, group
from app.graph.tasks import on_chord_error, add, xsum

c = (group(add.s(i, i) for i in range(1)) | xsum.s().on_error(on_chord_error.s())).delay()
```

tasks.py
```
@shared_task
def add(x, y):
    raise Exception("bob")

@shared_task
def xsum(numbers):
    return sum(numbers)

@shared_task
def on_chord_error(request, exc, traceback):
    print('calling this random error method!!!!')
    print('Task {0!r} raised error: {1!r}'.format(request.id, exc))
```

## Expected behavior
That the on_chord_error callback would be invoked and would print out "calling this random error method"

## Actual behavior
Whether I define an on_error callback or not (e.g. `c = (group(add.s(i, i) for i in range(1)) | xsum.s().on_error(on_chord_error.s())).delay()` versus `c = (group(add.s(i, i) for i in range(1)) | xsum.s()).delay()` , i get this same output:

output
```
django      | [2016-12-20 23:32:14,688: INFO/MainProcess] Received task: app.graph.tasks.add[c5eeb13a-21f6-4f15-ac22-eab0784d2806]
django      | [2016-12-20 23:32:16,068: ERROR/PoolWorker-2] Task app.graph.tasks.add[c5eeb13a-21f6-4f15-ac22-eab0784d2806] raised unexpected: Exception('bob',)
django      | Traceback (most recent call last):
django      |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 367, in trace_task
django      |     R = retval = fun(*args, **kwargs)
django      |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 622, in __protected_call__
django      |     return self.run(*args, **kwargs)
django      |   File "/usr/src/app/graph/tasks.py", line 44, in add
django      |     raise Exception("bob")
django      | Exception: bob
```
It never calls the on_error handler.

# normal circumstances work:
If I rewrite add from
```
@shared_task
def add(x, y):
    raise Exception("bob")
```
to this:
```
@shared_task
def add(x, y):
    return x + y
```

then everything works. So I believe one of three things is going on:
- the documentation regarding group / chord error handling is incorrect
- chord / group error handling does not work
- i'm misinterpreting how error handling is supposed to work in celery (i have scoured the internet for good examples, but i cannot find any good examples of people propagating errors from a group of subprocesses. I would think this would be a very common thing!)

### What is the celery equivalent of something like this from Node.js land? 
```
var async = require('async');
async.auto({
     thing1: function(){},
     thing2: function(){}
}, function(err, results) {
    if (err) {
         // do stuff!
   }
   // do normal stuff post batch of stuff
})
```

**Comment by NickStefan** [comment]
I am able to trigger the on_chord_error callback if I change add
from this  
```
@shared_task(bind=True)
def add(self, x, y):
    raise Exception('bob')
```
to this  
```
@shared_task(bind=True)
def add(self, x, y):
    self.update_state(state="FAILURE")
```

However, it doesnt call the on error callback with the correct arguments, AND it still calls the xsum method.

I still think this issue either points to missing documentation or a bug

**Comment by NickStefan** [comment]
I found the issue! This is definitely related #3574

**Comment by NickStefan** [comment]
#3597 also

**Comment by NickStefan** [comment]
the fix from here #3323 seems to have been related

**Comment by NickStefan** [comment]
callback and callback error doesn't work with one task (callback never called):
```
        callback = xsum.s().on_error(do_on_error.s())
        tasks = [ add.s(4, 4) ]
        c = chord(tasks)(callback)
```

callback and callback error does work with two tasks
```
        callback = xsum.s().on_error(do_on_error.s())
        tasks = [ add.s(4, 4), add.s(4, 5) ]
        c = chord(tasks)(callback)
```

**Comment by br1anjtuck** [comment]
Any new progress on this issue? I ran into the same issue that @NickStefan  experienced, and unless I am misinterpreting the documentation, it does seem like the callback should be called for proper chord error handling

**Comment by NickStefan** [comment]
@br1anjtuck we just made some helpers that always add a blank task when using chords (to ensure there are always at least 2 tasks)

```
@shared_task(bind=True)
def celery_bug_fix(self, *args, **kwargs):
    '''
    celery chords only correctly handle errors with at least 2 tasks, 
    so we always append a celery_bug_fix task
    https://github.com/celery/celery/issues/3709
    '''
    pass


```

**Comment by br1anjtuck** [comment]
Ok. So with the added helper task above, are you getting the user defined callback (your "do_on_error" task) to occur or are you getting a simple Chod Callback? (i.e. something like below):
```
Chord callback for '599a6689-3737-4e92-b774-9c4b56885fea' raised: ChordError(u"Dependency ec44e5c6-1396-44d9-acf7-86bdffaf0a10 raised RuntimeError('BLAH',)",)

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/backends/redis.py", line 281, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/lib/python2.7/site-packages/celery/backends/redis.py", line 234, in _unpack_chord_result
    raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
ChordError: Dependency ec44e5c6-1396-44d9-acf7-86bdffaf0a10 raised RuntimeError('BLAH',)",)
```

I am only getting the above chord callback error and I am not getting my defined callback error "on_chord_error" when I define the SAME tasks that you have from your first cell of this post, and run a group of to tasks chained to the "xsum" callback (exactly like you did in the second part of the cell before I first posted) : 
```
@shared_task
def on_chord_error(request, exc, traceback):
    print('\nTask {0!r} raised error: {1!r}\n'.format(request.id, exc))
```
I am supposed to getting this "on_chord_error" callback error, right? Or should it only be the Chord callback?

**Comment by NickStefan** [comment]
yes, i am getting the user defined callback when I always make sure to add a task (to ensure theres always at least two)

```
       callback = xsum.s().on_error(do_on_error.s())
        tasks = [ add.s(4, 4), celery_bug_fix.s() ]
        c = chord(tasks)(callback)
```

**Comment by br1anjtuck** [comment]
Hmm..interesting. I don't know why, but with the same code, I am only getting the Chord callback and am not getting the user-defined callback. The only time I get the user-defined callback error  is when I raise an exception in the "xsum" task rather than in the "add" task.

**Comment by br1anjtuck** [comment]
Are you doing the below instead of raising an exception in your task?:
```
@shared_task(bind=True)
def add(self, x, y):
    self.update_state(state="FAILURE")
```

**Comment by NickStefan** [comment]
Just doing regular exceptions. It was definitely tricky to get working, but yes an exception in add task is triggering the error callback

**Comment by xealot** [comment]
Yeah, I'm experiencing this as well. Seems to also be reported in https://github.com/celery/celery/issues/3317

**Comment by rholloway** [comment]
@br1anjtuck  did you ever figure out a solution to your problem? I seem to have the same situation as you with 4.0.2. My custom callback is called if the exception occurs in the chord callback (xsum), but if it occurs in individual task (add) it's never called.

I've tried sticking on_error onto each task in the header, onto the chord callback, onto the entire chord, everywhere. No luck.

**Comment by chrisbrantley** [comment]
I'm having the same problem. The `on_error` is simply never called. It doesn't seem to matter how many tasks I have in the group. Very frustrating.

**Comment by vitenbergd** [comment]
Dunno if it will be useful, but that's what i found out:

**test.py** 

```
import time
from celery import Celery
from celery.result import AsyncResult, GroupResult
from celery import group, chord

app = Celery('task', broker='redis://localhost:6379/0', backend='redis://localhost:6379/0')

@app.task
def ok():
    time.sleep(3)
    return True

@app.task
def err():
    raise ValueError

@app.task
def callback(res):
    print("Callback invoked: {0}".format(res))

@app.task
def errback0(request, exc, traceback):
    print("Chord error callback #0!")
    print('Task {0!r} raised error: {1!r}'.format(request.id, exc))

@app.task
def errback1():
    print("Chord error callback #1!")

@app.task
def errback2(*args, **kwargs):
    print("Chord error callback #2!")
    print("args:", *args)
    print("kwargs:", **kwargs)

@app.task
def errback3(arg):
    print("Chord error callback #3!")
    print("arg:", arg)
```

Now let's run some tasks.

**1** -  no **err.s()** tasks, so **callback.s()**  should be invoked

```
from test import *
cb = callback.s().on_error(errback0.s())
tasks = [ok.s() for i in range(3)]
res = chord(tasks)(cb)

```
Result: 
**1** - works as expected, callback task invoked, not so interesting


**2** - let's add some error task, same callbacks, errback0 - on_error callback implementation from documentation

```
tasks.append(err.s())
res = chord(tasks)(cb)
```
Result:
**2** - no callback were invoked. So, same issue as mentioned above


**3** - let's try another on_error callback, takes no arguments, and it's signature is immutable - **errback1**

```
cb = callback.s().on_error(errback1.si())
res = chord(tasks)(cb)
```
Result:
```
[2017-10-03 17:11:17,894: INFO/MainProcess] Received task: test.ok[d10d1c72-02e1-4618-a851-a267f7def2d2]  
[2017-10-03 17:11:17,895: INFO/MainProcess] Received task: test.ok[8cfa0ca4-2c41-450d-8509-47b1a9ff03c7]  
[2017-10-03 17:11:17,896: INFO/MainProcess] Received task: test.ok[0e5ec088-9a3d-49cb-a464-657783d5195c]  
[2017-10-03 17:11:17,897: INFO/MainProcess] Received task: test.err[2016f02d-e07c-487f-98bf-ad551f68cc49]  
[2017-10-03 17:11:17,899: ERROR/ForkPoolWorker-2] Task test.err[2016f02d-e07c-487f-98bf-ad551f68cc49] raised unexpected: ValueError()
Traceback (most recent call last):
  File "/home/dev/.virtualenvs/celery/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/dev/.virtualenvs/celery/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/dev/projects/python/celerytest/test.py", line 15, in err
    raise ValueError
ValueError
[2017-10-03 17:11:20,899: INFO/ForkPoolWorker-3] Task test.ok[0e5ec088-9a3d-49cb-a464-657783d5195c] succeeded in 3.0017932470000233s: True
[2017-10-03 17:11:20,900: INFO/ForkPoolWorker-4] Task test.ok[8cfa0ca4-2c41-450d-8509-47b1a9ff03c7] succeeded in 3.003801435999776s: True
[2017-10-03 17:11:20,900: ERROR/ForkPoolWorker-1] Chord callback for '70329930-11fe-4fc6-885f-9037e8e839c4' raised: ChordError("Dependency 2016f02d-e07c-487f-98bf-ad551f68cc49 raised ValueError('',)",)
Traceback (most recent call last):
  File "/home/dev/.virtualenvs/celery/lib/python3.6/site-packages/celery/backends/redis.py", line 290, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/home/dev/.virtualenvs/celery/lib/python3.6/site-packages/celery/backends/redis.py", line 290, in <listcomp>
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/home/dev/.virtualenvs/celery/lib/python3.6/site-packages/celery/backends/redis.py", line 243, in _unpack_chord_result
    raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
celery.exceptions.ChordError: Dependency 2016f02d-e07c-487f-98bf-ad551f68cc49 raised ValueError('',)
[2017-10-03 17:11:20,911: INFO/MainProcess] Received task: test.errback1[16f1dedf-4678-4def-98a9-2008a37a4223]  
[2017-10-03 17:11:20,911: INFO/ForkPoolWorker-1] Task test.ok[d10d1c72-02e1-4618-a851-a267f7def2d2] succeeded in 3.015284213997802s: True
[2017-10-03 17:11:20,912: WARNING/ForkPoolWorker-3] Chord error callback #1!
```
Result:
**3** - errback1 invoked, so i suppose we can do the same trick with errback0
```
cb = callback.s().on_error(errback0.si())
res = chord(tasks)(cb)
```
but it's not working. In case of immutable signature nothing is passed to error callback, but there are some args in the task difinition, so i suppose that is the reason of failure here.

**4** It seems like some arguments issue(?), ok let's try another one **errback2** and 
inspect arguments passed to error callback:
```
cb = callback.s().on_error(errback2.s())
res = chord(tasks)(cb)
```
Result:
**4** - Worked for me (some part of log is omitted):
```
[2017-10-03 17:12:09,478: WARNING/ForkPoolWorker-3] Chord error callback #2!
[2017-10-03 17:12:09,478: WARNING/ForkPoolWorker-3] args:
[2017-10-03 17:12:09,478: WARNING/ForkPoolWorker-3] 4a484b7c-d2e1-43c2-a4b0-8758a8caa896
[2017-10-03 17:12:09,478: WARNING/ForkPoolWorker-3] kwargs:
[2017-10-03 17:12:09,478: INFO/ForkPoolWorker-3] Task test.errback2[92683879-9164-402f-a691-0c08854dc1c7] succeeded in 0.0006017090017849114s: None

```
We can see here that it's only 1 argument with string, which is the id of chord's callback, so **errback3** will work abosuletly the same way.

I've tried **4.1/4.0.2** versions of celery.
So, you can:

- use on_error callback with immutable signature (if you don't care about the passed id of chord)
- use on_error callback with 1 argument

**Comment by listingmirror** [comment]
@vitenbergd thanks a bunch, that was spot on!

Switching to args/kwargs style arguments make the chord error callback work. I am on Python 3.6.2 for what it is worth..

So the question is, does code need fixed, or do we just need to update the docs?

**Comment by vitenbergd** [comment]
@listingmirror i think docs should be updated because there are two cases when **.on_error()** callback ivocation occures:

**example1 chord - group dependency fail** 
`chord([ok_task.s(), fail_task.s()])(my_cool_callback.si().on_error(not_so_cool_callback.s()))`
**example2 chord - callback fail** 
`chord([ok_task.s(), fail_task.s()])(my_fail_callback.si().on_error(not_so_cool_callback.s()))`

* ChordError - when one of the group dependencies fails (**example1**),  then the only argument passed to 
**not_so_cool_callback** is string with **my_cool_callback's** id, cause **my_cool_callback** was never called and no task context(request) can be passed, i suppose (as metioned in docs):
`
@app.task
def on_chord_error(request, exc, traceback):
    print('Task {0!r} raised error: {1!r}'.format(request.id, exc))
`
And also in that case **not_so_cool_callback** will be executed as separate task.
* Any **my_fail_callback** (**example2**, some uncaught exception raised from **my_fail_callback**) failure will cause **not_so_cool_callback** invocation, but it seems like it acts like **on_failure** task handler in the context of **my_fail_callback**, so it's not a separate task anymore, and request, exception and traceback can be passed to **not_so_cool_callback** as docs example.

**Comment by auvipy** [comment]
can anyone verify the status on master branch?

**Comment by xirdneh** [comment]
Are there any current efforts on this?

**Comment by xirdneh** [comment]
I've been doing some testing on this.
The callback is getting called on error with different types of chords.
Still documentation is wrong because the error task gets called only with a result id.
The result id corresponds to the `ChordError` result. The documentation states that a `request`, `exc` and `traceback` will get passed to the error callback.

**Comment by fjsj** [comment]
@auvipy Debugging some of this, behavior of `CE + chord(tasks)(callback.s().on_error(errcb_args.s()))` is definitely wrong as per docs. Relevant code seems to be here: https://github.com/celery/celery/blob/9ba426a0af698e574ee52b1d5197798a50c87f87/celery/backends/base.py#L239 (this is current master code, so it's still wrong)

**Comment by dalmarcogd** [comment]
+1

**Comment by medihack** [comment]
I also stumbled into this problem. The documentation seems to be just wrong here and it took me some hours to figure this out. 
A chord error callback (in a Django app) like below works perfectly for me, too.

    @shared_task
    def err_callback(*args, **kwargs):
        task_id = args[0]
        my_data = kwargs['my_data']

**Comment by auvipy** [comment]
> I also stumbled into this problem. The documentation seems to be just wrong here and it took me some hours to figure this out.
> A chord error callback (in a Django app) like below works perfectly for me, too.
> 
> ```
> @shared_task
> def err_callback(*args, **kwargs):
>     task_id = args[0]
>     my_data = kwargs['my_data']
> ```

would you mind sending a PR for changing the doc?

**Comment by OndrejIT** [comment]
Its work fine for me:

	workflow = chord(group(tasks),
		callback_x_task(url=data["callback"], data=request.data, status="done"),
	).on_error(group((
		callback_x_task(url=data["callback"], data=request.data, status="failed"),
		callback_task(url=t.api_url, status=Status.FAILED),
	)))

or:

	workflow = chord(
		task,
		callback_x_task(url=data["callback"], data=request.data, status="done"),
	).on_error(group((
		callback_x_task(url=data["callback"], data=request.data, status="failed"),
		callback_task(url=t.api_url, status=Status.FAILED),
	)))

...

	workflow = chord(
		workflow,
		callback_task(url=t.api_url, status=Status.DONE),
	)

	workflow.delay()

Maybe some examples in docs is wrong?..

**Comment by auvipy** [comment]
> Its work fine for me:
> 
> ```
> workflow = chord(group(tasks),
> 	callback_x_task(url=data["callback"], data=request.data, status="done"),
> ).on_error(group((
> 	callback_x_task(url=data["callback"], data=request.data, status="failed"),
> 	callback_task(url=t.api_url, status=Status.FAILED),
> )))
> ```
> 
> or:
> 
> ```
> workflow = chord(
> 	task,
> 	callback_x_task(url=data["callback"], data=request.data, status="done"),
> ).on_error(group((
> 	callback_x_task(url=data["callback"], data=request.data, status="failed"),
> 	callback_task(url=t.api_url, status=Status.FAILED),
> )))
> ```
> 
> ...
> 
> ```
> workflow = chord(
> 	workflow,
> 	callback_task(url=t.api_url, status=Status.DONE),
> )
> 
> workflow.delay()
> ```
> 
> Maybe some examples in docs is wrong?..

can you send a doc improvement PR?

**Comment by OndrejIT** [comment]
on_error isn't work fine.
When i not use group in error_callback problem persistent..

Callback called:
	workflow = chain(
		*tasks,
		callback_task(url=t.api_url, status=Status.DONE),
	).on_error(group(callback_task(url=t.api_url, data={"status": Status.FAILED})))

Callback doesn't called:
	workflow = chain(
		*tasks,
		callback_task(url=t.api_url, status=Status.DONE),
	).on_error(callback_task(url=t.api_url, data={"status": Status.FAILED}))

**Comment by thedrow** [comment]
@maybe-sybr If you have a moment, please take a look.

**Comment by maybe-sybr** [comment]
I haven't had time to look into this but I do recall that last year we fixed some cases where callbacks and errbacks would not be passed up from a canvas element being wrapped in a chord/chain. I think the best approach would be to take some of the example cases in this issue and check if we have equivalent tests. This would be a good first issue for someone interested in learning about the canvas system. Pinging @thedrow for potential redistribution.

**Comment by aakash2610** [comment]
I am facing the same issue. Is there any workaround or solution which is suggested by the celery team? I tried args and kwargs thing mentioned above which only passes the callback id. It does not fulfil my requirement.

My requirement is if any task in the chord header fails, the error callback should be called with the error and traceback of the failed task. Is there any to achieve this? 

I am using celery v4.4.7.

**Comment by AbdoulNdiaye** [comment]
I confirm that in version celery==5.0.5 this bug still persists.
I tried using on_error on every constellationi could think of and on_error callback isn't firing.

**Comment by thedrow** [comment]
Since we fixed a few bugs in that area, could you please verify that this reproduces on master as well?

**Comment by Ixiodor** [comment]
Still here? ( 5.1.2)
I'm doing a chain of some task and link works and on_error dosn't.
I used to use that way in the past and worked ( but I was using some tricks to escape from chord upgrade)

**Comment by auvipy** [comment]
try 5.2.0rc1 please

**Comment by rca** [comment]
I can confirm this appears to work with v5.2.1 using this task: 

```python
@shared_task(base=ClassificationTasks)
def taskie(*args, **kwargs):
    message = f"args={args}, kwargs={kwargs}"

    if "raises" in kwargs:
        raise Exception(message)
    else:
        print(message)
```

With that fake task this chord does call the error handler: 

```python
>>> f = chain(taskie.s(m='f1', raises=True), taskie.s(m='f2'))
>>> s = chain(taskie.s(m='s1'), taskie.s(m='s2'))
>>> g = group(f, s)
>>> r = chord(g)(taskie.s(m='chord done').on_error(taskie.s(m='chord error')))
>>> r.state
'FAILURE'
```

The celery worker log is below; note the task with `'kwargs': {'m': 'chord error'}` is called  🎉 

This seems to be working for my testing use-case; we'll be trying this with real tasks shortly.  If anything goes sideways I'll report back.

Thanks!

```
[2021-11-18 18:16:40,543: INFO/MainProcess] Task classification.tasks.taskie[7ce2a516-3657-4979-83a9-acef65695f4c] received
[2021-11-18 18:16:40,543: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7fd7a367fdc0> (args:('classification.tasks.taskie', '7ce2a516-3657-4979-83a9-acef65695f4c', {'lang': 'py', 'task': 'classification.tasks.taskie', 'id': '7ce2a516-3657-4979-83a9-acef65695f4c', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '7ce2a516-3657-4979-83a9-acef65695f4c', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': "{'m': 'f1', 'raises': True}", 'origin': 'gen8@b9eebe8d960d', 'ignore_result': False, 'sentry-trace': '97b6a7d5f7464f26b87835bec9bfcb51-9f2c47650b89eee9-', 'headers': {'sentry-trace': '97b6a7d5f7464f26b87835bec9bfcb51-9f2c47650b89eee9-'}, 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'lang': 'py', 'task': 'classification.tasks.taskie', 'id': '7ce2a516-3657-4979-83a9-acef65695f4c', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '7ce2a516-3657-4979-83a9-acef65695f4c',... kwargs:{})
[2021-11-18 18:16:40,551: WARNING/ForkPoolWorker-1] failure info :
{'name': 'classification.tasks.taskie', 'exc': Exception("args=(), kwargs={'m': 'f1', 'raises': True}"), 'task_id': '7ce2a516-3657-4979-83a9-acef65695f4c', 'args': [], 'kwargs': {'m': 'f1', 'raises': True}, 'einfo': <ExceptionInfo: Exception("args=(), kwargs={'m': 'f1', 'raises': True}")>}
[2021-11-18 18:16:40,552: ERROR/ForkPoolWorker-1] Task classification.tasks.taskie[7ce2a516-3657-4979-83a9-acef65695f4c] raised unexpected: Exception("args=(), kwargs={'m': 'f1', 'raises': True}")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/opt/project/src/classification/tasks.py", line 54, in taskie
    raise Exception(message)
Exception: args=(), kwargs={'m': 'f1', 'raises': True}
[2021-11-18 18:16:40,556: INFO/MainProcess] Task classification.tasks.taskie[79d86b01-245f-4f70-b1b2-d5263f0b185f] received
[2021-11-18 18:16:40,556: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7fd7a367fdc0> (args:('classification.tasks.taskie', '79d86b01-245f-4f70-b1b2-d5263f0b185f', {'lang': 'py', 'task': 'classification.tasks.taskie', 'id': '79d86b01-245f-4f70-b1b2-d5263f0b185f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '79d86b01-245f-4f70-b1b2-d5263f0b185f', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': "{'m': 's1'}", 'origin': 'gen8@b9eebe8d960d', 'ignore_result': False, 'sentry-trace': '9f233afc104740f7a83e20fb23ae8dde-be8c9f13aacee9eb-', 'headers': {'sentry-trace': '9f233afc104740f7a83e20fb23ae8dde-be8c9f13aacee9eb-'}, 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'lang': 'py', 'task': 'classification.tasks.taskie', 'id': '79d86b01-245f-4f70-b1b2-d5263f0b185f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '79d86b01-245f-4f70-b1b2-d5263f0b185f', 'parent_id': None,... kwargs:{})
[2021-11-18 18:16:40,558: WARNING/ForkPoolWorker-1] args=(), kwargs={'m': 's1'}
[2021-11-18 18:16:40,560: WARNING/ForkPoolWorker-1] success info :
 {'self': <@task: classification.tasks.taskie of webapp at 0x7fd7a35aaeb0>, 'retval': None, 'task_id': '79d86b01-245f-4f70-b1b2-d5263f0b185f', 'args': [], 'kwargs': {'m': 's1'}}
[2021-11-18 18:16:40,560: INFO/ForkPoolWorker-1] Task classification.tasks.taskie[79d86b01-245f-4f70-b1b2-d5263f0b185f] succeeded in 0.0025514820008538663s: None
[2021-11-18 18:16:40,562: INFO/MainProcess] Task classification.tasks.taskie[b641153f-3a2f-49da-b4b4-50d5ae7b6cb4] received
[2021-11-18 18:16:40,563: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7fd7a367fdc0> (args:('classification.tasks.taskie', 'b641153f-3a2f-49da-b4b4-50d5ae7b6cb4', {'lang': 'py', 'task': 'classification.tasks.taskie', 'id': 'b641153f-3a2f-49da-b4b4-50d5ae7b6cb4', 'shadow': None, 'eta': None, 'expires': None, 'group': 'bbd69ea2-7886-4d05-b5c9-0c301ab41390', 'group_index': 1, 'retries': 0, 'timelimit': [None, None], 'root_id': '79d86b01-245f-4f70-b1b2-d5263f0b185f', 'parent_id': '79d86b01-245f-4f70-b1b2-d5263f0b185f', 'argsrepr': '(None,)', 'kwargsrepr': "{'m': 's2'}", 'origin': 'gen25@83743059cccd', 'ignore_result': False, 'sentry-trace': '9f233afc104740f7a83e20fb23ae8dde-990f4a9db4501057-0', 'headers': {'sentry-trace': '9f233afc104740f7a83e20fb23ae8dde-990f4a9db4501057-0'}, 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'lang': 'py', 'task': 'classification.tasks.taskie', 'id': 'b641153f-3a2f-49da-b4b4-50d5ae7b6cb4', 'shadow': None, 'eta': None, 'expires': None, 'group': 'bbd69ea2-7886-4d05-b5c9-0c301ab41390', 'group_index': 1, 'retries': 0,... kwargs:{})
[2021-11-18 18:16:40,564: WARNING/ForkPoolWorker-1] args=(None,), kwargs={'m': 's2'}
[2021-11-18 18:16:40,566: ERROR/ForkPoolWorker-1] Chord 'bbd69ea2-7886-4d05-b5c9-0c301ab41390' raised: ChordError('Dependency e0fd69e2-6712-436d-8b7d-56006401af15 raised Exception("args=(), kwargs={\'m\': \'f1\', \'raises\': True}")')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in on_chord_part_return
    resl = [unpack(tup, decode) for tup in resl]
  File "/usr/local/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in <listcomp>
    resl = [unpack(tup, decode) for tup in resl]
  File "/usr/local/lib/python3.9/site-packages/celery/backends/redis.py", line 426, in _unpack_chord_result
    raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency e0fd69e2-6712-436d-8b7d-56006401af15 raised Exception("args=(), kwargs={'m': 'f1', 'raises': True}")
[2021-11-18 18:16:40,569: WARNING/ForkPoolWorker-1] args=(<Context: {'id': 'eced0e73-6489-4379-a01c-c396f8530b13', 'errbacks': [{'task': 'classification.tasks.taskie', 'args': [], 'kwargs': {'m': 'chord error'}, 'options': {}, 'subtask_type': None, 'immutable': False}], 'delivery_info': {}, 'task': 'classification.tasks.taskie', 'args': [], 'kwargs': {'m': 'chord done'}, 'options': {'link_error': [{'task': 'classification.tasks.taskie', 'args': [], 'kwargs': {'m': 'chord error'}, 'options': {}, 'subtask_type': None, 'immutable': False}], 'task_id': 'eced0e73-6489-4379-a01c-c396f8530b13', 'reply_to': 'd0b24bfa-71ca-32cb-8d47-55d377d1385d'}, 'subtask_type': None, 'immutable': False}>, ChordError('Dependency e0fd69e2-6712-436d-8b7d-56006401af15 raised Exception("args=(), kwargs={\'m\': \'f1\', \'raises\': True}")'), None), kwargs={'m': 'chord error'}
[2021-11-18 18:16:40,570: WARNING/ForkPoolWorker-1] success info :
 {'self': <@task: classification.tasks.taskie of webapp at 0x7fd7a35aaeb0>, 'retval': None, 'task_id': 'b641153f-3a2f-49da-b4b4-50d5ae7b6cb4', 'args': [None], 'kwargs': {'m': 's2'}}
[2021-11-18 18:16:40,570: INFO/ForkPoolWorker-1] Task classification.tasks.taskie[b641153f-3a2f-49da-b4b4-50d5ae7b6cb4] succeeded in 0.0064229569979943335s: None
```

**Comment by auvipy** [comment]
thank you. and please report back again

**Comment by NicolasM-Forsk** [comment]
I think the documentation is still outdated: 
https://docs.celeryproject.org/en/master/userguide/canvas.html

**Comment by nmoreaud** [comment]
I think the documentation is still outdated:
https://docs.celeryproject.org/en/master/userguide/canvas.html

```
>>> c = (group(add.s(i, i) for i in range(10)) |
...      xsum.s().on_error(on_chord_error.s())).delay()

@app.task
def on_chord_error(request, exc, traceback):
    print('Task {0!r} raised error: {1!r}'.format(request.id, exc))
```

Whereas in this ticket, working error callback uses `*args` and `**kwargs`

**Comment by auvipy** [comment]
can you please send a PR to imrove/update the docs?

**Comment by nmoreaud** [comment]
Ok after some checks the documentation seems correct for unbound tasks, but not for bound tasks. 

1 --------------
The code handles 2 incompatible argument schemes, it can either pass `request, exc, traceback` or `request_id` to callbacks.
It may be worth mentionning in the documentation?

The following signatures are compatible with `on_error(on_chord_error.s())`:
- `def on_chord_error(request, exc, traceback)`
- `def on_chord_error(request_id)`.

The following declarations are compatible with: `on_error(on_chord_error.s(123))`, :
- `def on_chord_error(request, exc, traceback, custom)`.
- `def on_chord_error(request_id, custom):`

2 --------------
If I use `bind=True` :
- `def on_chord_error(self, request, exc, traceback)` is **KO** (`TypeError: on_chord_error() missing 2 required positional arguments: 'exc' and 'traceback'`)
- `def on_chord_error(self, request_id, custom)` is OK

Same thing happens if a add a custom argument.
I am just learning Celery so it can be a mistake, but 2nd point looks like a bug.

3 --------------
For some reason if I process a group with more than 2 items, chord never finishes (with celery 5.1.2, rabbitMQ 3.9.9, Mongo 5.0.4)
(I use amqp://...... rabbitmq broker and mongodb://... result backend)
There is an open ticket (https://github.com/celery/celery/issues/4701) but the logs are not the same and there is no warning in documentation showing that chords implementation is not compatible yet with mongodb result backend.

Typical log:
```
[2022-01-24 12:12:51,666: INFO/MainProcess] celery@worker1 ready.
[2022-01-24 12:12:53,762: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
[2022-01-24 12:12:53,762: INFO/MainProcess] Task test_celery.add[fb83685b-38b9-4baa-8006-4758fc4e2d64] received
[2022-01-24 12:12:53,763: INFO/MainProcess] Task test_celery.add[db1cde84-1431-4ea2-9786-7de0f1b81d6c] received
[2022-01-24 12:12:53,786: INFO/ForkPoolWorker-16] Task test_celery.add[db1cde84-1431-4ea2-9786-7de0f1b81d6c] succeeded in 0.02320910000707954s: 2
[2022-01-24 12:12:53,786: INFO/ForkPoolWorker-15] Task test_celery.add[fb83685b-38b9-4baa-8006-4758fc4e2d64] succeeded in 0.0232757999910973s: 0
[2022-01-24 12:12:55,685: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
[2022-01-24 12:12:55,686: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
[2022-01-24 12:12:57,676: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
[2022-01-24 12:12:57,677: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
[2022-01-24 12:12:59,679: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
[2022-01-24 12:12:59,680: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
[2022-01-24 12:13:01,657: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
[2022-01-24 12:13:01,658: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
[2022-01-24 12:13:03,682: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
[2022-01-24 12:13:03,683: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
[2022-01-24 12:13:05,684: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
[2022-01-24 12:13:05,685: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
... (infinite loop)
```

**Comment by AbdealiJK** [comment]
I can confirm that I also see Point 2A in https://github.com/celery/celery/issues/3709#issuecomment-1019995867 :
i.e. If I use `bind=True` with `def on_chord_error(self, request, exc, traceback)` it gives `TypeError: on_chord_error() missing 2 required positional arguments: 'exc' and 'traceback'`

**Comment by Miraliu** [comment]
> Ok after some checks the documentation seems correct for unbound tasks, but not for bound tasks.
> 
> 1 -------------- The code handles 2 incompatible argument schemes, it can either pass `request, exc, traceback` or `request_id` to callbacks. It may be worth mentionning in the documentation?
> 
> The following declarations are compatible with `on_error(on_chord_error.s())`:
> 
> * `def on_chord_error(request, exc, traceback)`
> * `def on_chord_error(request_id)`.
> 
> The following declarations are compatible with: `on_error(on_chord_error.s(123))`, :
> 
> * `def on_chord_error(request, exc, traceback, custom)`.
> * `def on_chord_error(request_id, custom):`
> 
> 2 -------------- If I use `bind=True` :
> 
> * `def on_chord_error(self, request, exc, traceback)` is **KO** (`TypeError: on_chord_error() missing 2 required positional arguments: 'exc' and 'traceback'`)
> * `def on_chord_error(self, request_id, custom)` is OK
> 
> Same thing happens if I add a custom argument. I am just learning Celery so it can be a mistake, but 2nd point looks like a bug.
> 
> 3 -------------- For some reason if I process a group with more than 2 items, chord never finishes (with celery 5.1.2, rabbitMQ 3.9.9, Mongo 5.0.4) (I use amqp://...... rabbitmq broker and mongodb://... result backend) There is an open ticket (#4701) but the logs are not the same and there is no warning in documentation showing that chords implementation is not compatible yet with mongodb result backend.
> 
> Typical log:
> 
> ```
> [2022-01-24 12:12:51,666: INFO/MainProcess] celery@worker1 ready.
> [2022-01-24 12:12:53,762: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
> [2022-01-24 12:12:53,762: INFO/MainProcess] Task test_celery.add[fb83685b-38b9-4baa-8006-4758fc4e2d64] received
> [2022-01-24 12:12:53,763: INFO/MainProcess] Task test_celery.add[db1cde84-1431-4ea2-9786-7de0f1b81d6c] received
> [2022-01-24 12:12:53,786: INFO/ForkPoolWorker-16] Task test_celery.add[db1cde84-1431-4ea2-9786-7de0f1b81d6c] succeeded in 0.02320910000707954s: 2
> [2022-01-24 12:12:53,786: INFO/ForkPoolWorker-15] Task test_celery.add[fb83685b-38b9-4baa-8006-4758fc4e2d64] succeeded in 0.0232757999910973s: 0
> [2022-01-24 12:12:55,685: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
> [2022-01-24 12:12:55,686: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
> [2022-01-24 12:12:57,676: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
> [2022-01-24 12:12:57,677: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
> [2022-01-24 12:12:59,679: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
> [2022-01-24 12:12:59,680: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
> [2022-01-24 12:13:01,657: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
> [2022-01-24 12:13:01,658: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
> [2022-01-24 12:13:03,682: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
> [2022-01-24 12:13:03,683: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
> [2022-01-24 12:13:05,684: INFO/ForkPoolWorker-15] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] retry: Retry in 1.0s
> [2022-01-24 12:13:05,685: INFO/MainProcess] Task celery.chord_unlock[e2d97e9e-1747-429d-aa01-65724ba6bfcd] received
> ... (infinite loop)
> ```

celery==5.3.1
def on_chord_error(request_id, custom) no longer works for us...the callback is not invoked.
def on_chord_error(request, exc, traceback, custom) works.
