### ISSUE TITLE
Successful tasks are not acked if acks_late=True on warm shutdown.

### ISSUE THREAD

**Issue by sww** [celery/celery#3802]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
$ celery -A app report

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.4.3
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: 'redis://127.0.0.1:6379/3'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Tasks that finish and succeed after the warm shutdown signal are not acked if `acks_late=True`. To reproduce:

1. Create `app.py`:
```python
from time import sleep

from celery import Celery

app = Celery('foo', broker='redis://127.0.0.1:6379/3')

@app.task(acks_late=True)
def foo():
    sleep(5)
    return 'foo'
```
2. Queue up a task:
```bash
$ python -c "from app import foo; foo.apply_async()"
```
3. Start the worker and issue a warm shutdown (CTRL+C) before the task finishes.
```
$ celery -A app worker --loglevel=debug
[2017-01-30 16:23:46,092: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2017-01-30 16:23:46,094: DEBUG/MainProcess] | Worker: Building graph...
[2017-01-30 16:23:46,094: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, StateDB, Beat, Consumer}
[2017-01-30 16:23:46,108: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2017-01-30 16:23:46,109: DEBUG/MainProcess] | Consumer: Building graph...
[2017-01-30 16:23:46,124: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Gossip, Agent, Tasks, Control, Heart, event loop}



celery@foobar v4.0.2 (latentcall)

Darwin-16.3.0-x86_64-i386-64bit 2017-01-30 16:23:46

[config]
.> app:         foo:0x1034ddc88
.> transport:   redis://127.0.0.1:6379/3
.> results:     disabled://
.> concurrency: 4 (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)

[queues]
.> celery           exchange=celery(direct) key=celery


[tasks]
  . app.foo
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap

[2017-01-30 16:23:46,139: DEBUG/MainProcess] | Worker: Starting Hub
[2017-01-30 16:23:46,139: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:46,140: DEBUG/MainProcess] | Worker: Starting Pool
[2017-01-30 16:23:46,248: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:46,249: DEBUG/MainProcess] | Worker: Starting Consumer
[2017-01-30 16:23:46,250: DEBUG/MainProcess] | Consumer: Starting Connection
[2017-01-30 16:23:46,268: INFO/MainProcess] Connected to redis://127.0.0.1:6379/3
[2017-01-30 16:23:46,268: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:46,269: DEBUG/MainProcess] | Consumer: Starting Events
[2017-01-30 16:23:46,278: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:46,278: DEBUG/MainProcess] | Consumer: Starting Mingle
[2017-01-30 16:23:46,278: INFO/MainProcess] mingle: searching for neighbors
[2017-01-30 16:23:47,309: INFO/MainProcess] mingle: all alone
[2017-01-30 16:23:47,309: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:47,309: DEBUG/MainProcess] | Consumer: Starting Gossip
[2017-01-30 16:23:47,316: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:47,316: DEBUG/MainProcess] | Consumer: Starting Tasks
[2017-01-30 16:23:47,320: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:47,320: DEBUG/MainProcess] | Consumer: Starting Control
[2017-01-30 16:23:47,325: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:47,325: DEBUG/MainProcess] | Consumer: Starting Heart
[2017-01-30 16:23:47,329: DEBUG/MainProcess] ^-- substep ok
[2017-01-30 16:23:47,329: DEBUG/MainProcess] | Consumer: Starting event loop
[2017-01-30 16:23:47,329: INFO/MainProcess] celery@foobar ready.
[2017-01-30 16:23:47,330: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2017-01-30 16:23:47,330: DEBUG/MainProcess] basic.qos: prefetch_count->16
[2017-01-30 16:23:48,093: INFO/MainProcess] Received task: app.foo[a1d83951-0e24-488b-b400-0ddbd4161254]
[2017-01-30 16:23:48,093: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10357c598> (args:('app.foo', 'a1d83951-0e24-488b-b400-0ddbd4161254', {'kwargsrepr': '{}', 'id': 'a1d83951-0e24-488b-b400-0ddbd4161254', 'task': 'app.foo', 'expires': None, 'reply_to': '6de20f21-2460-3189-b534-29ae63c15d1c', 'lang': 'py', 'group': None, 'argsrepr': '()', 'eta': None, 'retries': 0, 'delivery_info': {'exchange': '', 'redelivered': None, 'routing_key': 'celery', 'priority': 0}, 'root_id': 'a1d83951-0e24-488b-b400-0ddbd4161254', 'correlation_id': 'a1d83951-0e24-488b-b400-0ddbd4161254', 'origin': 'gen52076@foobar', 'timelimit': [None, None], 'parent_id': None}, b'[[], {}, {"chord": null, "callbacks": null, "chain": null, "errbacks": null}]', 'application/json', 'utf-8') kwargs:{})
[2017-01-30 16:23:48,095: DEBUG/MainProcess] Task accepted: app.foo[a1d83951-0e24-488b-b400-0ddbd4161254] pid:52112
^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
[2017-01-30 16:23:49,613: DEBUG/MainProcess] | Worker: Closing Hub...
[2017-01-30 16:23:49,613: DEBUG/MainProcess] | Worker: Closing Pool...
[2017-01-30 16:23:49,614: DEBUG/MainProcess] | Worker: Closing Consumer...
[2017-01-30 16:23:49,614: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2017-01-30 16:23:49,614: DEBUG/MainProcess] | Consumer: Closing Connection...
[2017-01-30 16:23:49,614: DEBUG/MainProcess] | Consumer: Closing Events...
[2017-01-30 16:23:49,614: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2017-01-30 16:23:49,614: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2017-01-30 16:23:49,614: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2017-01-30 16:23:49,615: DEBUG/MainProcess] | Consumer: Closing Control...
[2017-01-30 16:23:49,615: DEBUG/MainProcess] | Consumer: Closing Heart...
[2017-01-30 16:23:49,615: DEBUG/MainProcess] | Consumer: Closing event loop...
[2017-01-30 16:23:49,615: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2017-01-30 16:23:49,615: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2017-01-30 16:23:49,617: DEBUG/MainProcess] | Consumer: Stopping Control...
[2017-01-30 16:23:49,620: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2017-01-30 16:23:49,620: DEBUG/MainProcess] Canceling task consumer...
[2017-01-30 16:23:49,621: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2017-01-30 16:23:49,624: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2017-01-30 16:23:49,624: DEBUG/MainProcess] | Consumer: Stopping Events...
[2017-01-30 16:23:49,624: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2017-01-30 16:23:49,625: DEBUG/MainProcess] | Worker: Stopping Pool...
[2017-01-30 16:23:53,099: INFO/PoolWorker-2] Task app.foo[a1d83951-0e24-488b-b400-0ddbd4161254] succeeded in 5.002987815998495s: 'foo'
[2017-01-30 16:23:54,103: DEBUG/MainProcess] | Worker: Stopping Hub...
[2017-01-30 16:23:54,103: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2017-01-30 16:23:54,104: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2017-01-30 16:23:54,104: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2017-01-30 16:23:54,104: DEBUG/MainProcess] Canceling task consumer...
[2017-01-30 16:23:54,104: DEBUG/MainProcess] Closing consumer channel...
[2017-01-30 16:23:54,104: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2017-01-30 16:23:54,104: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2017-01-30 16:23:54,105: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2017-01-30 16:23:54,106: WARNING/MainProcess] Restoring 1 unacknowledged message(s)
[2017-01-30 16:23:54,111: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
```
(Note the second to last line even after the log says the task succeded.)

## Expected behavior

The task is acked before exit.

## Actual behavior

The task is not acked and restored. The next time the worker starts up, the same task will be executed again.

**Comment by markine** [comment]
I wonder if this is related to https://github.com/celery/celery/issues/3796

**Comment by calvinwyoung** [comment]
We're running into this issue as well. All long-running tasks that we kill gracefully mid-execution will get requeued, even if they complete successfully.

Has anyone made progress on this?

**Comment by dejlek** [comment]
I can confirm this is happening with Celery 4.0.2 (Redis backend)

**Comment by daviddavis** [comment]
FWIW, I just reproduced this problem with rabbitmq and no redis backend.

**Comment by cristianocca** [comment]
I'm using RabbitMQ and I notice as well that warm shut downs will requeue tasks with acks_late=True. However, it seems to me that warm shut down is actually killing the task as well, not really letting it finish, which is probably the reason it is queued back.

My question is, shouldn't warm shutdown ALWAYS allow the task to finish, even with acks_late=True and also ack the task once it completes, rather than killing it mid progress? I couldn't find more info about warm shutdowns and acks_late=True behavior anywhere, can anyone shine some light here?

**Comment by cristianocca** [comment]
After testing more, doing a warm shutdown without killing the actual workers, I get the task succeed log and yet it's never acked, and it is queued again once celery is started. This is quite bad and so far the only work around for some "critical" tasks that must always run and yet avoid duplicates as much as possible, is to store w/e task id it was queued with, and clear the task id once the job is done, and then always check for a non empty task id when the task starts.

Are there any other work arounds for this? Is this something that might be fixed soon?

**Comment by alexmic** [comment]
Similar issue here, although our configuration is to ack early (the default). What seems to have happened is that a task was pre-fetched by the worker, the worker received a TERM, the task started executing just after and successfully finished, the worker restarted and when it came back it received the same task again. 

Here's a trace of our logs to illustrate:
```
16:37:47,299 celery.worker.strategy INFO [-]: Received task: ***[c341fea7-12a0-457c-bfab-65290ceeaab3] <- Task prefetched
1/Dec/2017:16:38:13 *** info worker: Warm shutdown (MainProcess) <- TERM 
16:38:14,347 plum.common.clients.http.base INFO [c341fea7-12a0-457c-bfab-65290ceeaab3]: HTTP client request: ... <- Task execution starts
16:38:14,733 celery.app.trace INFO [c341fea7-12a0-457c-bfab-65290ceeaab3]: Task ***[c341fea7-12a0-457c-bfab-65290ceeaab3] succeeded in 0.571790334997786s: None <- Task finished successfully 
1/Dec/2017:16:38:27 *** info  -------------- celery@878351b1-1a45-429d-b912-58f72dd1058b v4.1.0 (latentcall) <- worker restarted
16:38:27,610 celery.worker.strategy INFO [-]: Received task: task.accounts.transfer_deposit_from_receivables[c341fea7-12a0-457c-bfab-65290ceeaab3]  <- same task received again (note task id)
```

**Comment by auvipy** [comment]
if anyone can verify the issue on latest master branch using the latest dependencies?

**Comment by drien** [comment]
I'm able to reproduce with latest master (f3ef0df5a6e4008d73fdc6e7b6c02c7edf361d5a) and rabbitmq.

Here's the output, I ran the same kind of `sleep()` task as the OP with a couple of extra log messages:

```
...
[2018-02-20 18:28:08,873: INFO/MainProcess] Connected to amqp://user:**@some-rabbit:5672/testhost
[2018-02-20 18:28:08,888: INFO/MainProcess] mingle: searching for neighbors
[2018-02-20 18:28:09,948: INFO/MainProcess] mingle: all alone
[2018-02-20 18:28:09,981: INFO/MainProcess] celery@d920d5fc20d2 ready.
[2018-02-20 18:28:42,780: INFO/MainProcess] Received task: celeryapp.foo[e4b9ce2e-1bff-460d-b18f-033f50c2c90e]  
[2018-02-20 18:28:42,783: WARNING/ForkPoolWorker-2] Starting Task
^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
[2018-02-20 18:28:47,791: WARNING/ForkPoolWorker-2] Finished Sleeping
[2018-02-20 18:28:47,792: INFO/ForkPoolWorker-2] Task celeryapp.foo[e4b9ce2e-1bff-460d-b18f-033f50c2c90e] succeeded in 5.010052320998511s: 'foo'


...



/opt/celery/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
 
 -------------- celery@0bc72f9325b0 v4.2.0 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-4.9.60-linuxkit-aufs-x86_64-with-debian-9.3 2018-02-20 18:28:57
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         foo:0x7f694179c6d8
- ** ---------- .> transport:   amqp://user:**@some-rabbit:5672/testhost
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . celeryapp.foo

[2018-02-20 18:28:57,634: INFO/MainProcess] Connected to amqp://user:**@some-rabbit:5672/testhost
[2018-02-20 18:28:57,650: INFO/MainProcess] mingle: searching for neighbors
[2018-02-20 18:28:58,689: INFO/MainProcess] mingle: all alone
[2018-02-20 18:28:58,760: INFO/MainProcess] celery@0bc72f9325b0 ready.
[2018-02-20 18:28:58,762: INFO/MainProcess] Received task: celeryapp.foo[e4b9ce2e-1bff-460d-b18f-033f50c2c90e]  
[2018-02-20 18:28:58,867: WARNING/ForkPoolWorker-2] Starting Task
[2018-02-20 18:29:03,873: WARNING/ForkPoolWorker-2] Finished Sleeping
[2018-02-20 18:29:03,874: INFO/ForkPoolWorker-2] Task celeryapp.foo[e4b9ce2e-1bff-460d-b18f-033f50c2c90e] succeeded in 5.007625436002854s: 'foo'
```

(Also hi there @alexmic! 👋)

**Comment by lovemyliwu** [comment]
@sww I just do a tricky work and fixed this problem, please check

https://gist.github.com/lovemyliwu/af5112de25b594205a76c3bfd00b9340

**Comment by crazeekennee** [comment]
I battled this for a few days, googling like crazy, tripping through python code, and thinking I must have screwed something up.

Finally, I found finding the magic spell that seems to have patched this issue on my end: I downgraded celery to 4.1.1.

Note: patch != solution

Hope this helps someone else.

**Comment by auvipy** [comment]
so this is a regression

**Comment by max-l** [comment]
I'm getting this problem with celery 4.2.0 
1. a task with ack_late=True is sent to a queue 
2. the task completes
3. the worker is terminated with CTRL+C (running in the foreground)
4. when the worker is restarted, the task is resubmited

**Comment by wjcgithub** [comment]
When will it be released 4.3?

**Comment by ksonj** [comment]
Might be fixed by https://github.com/celery/kombu/pull/926

**Comment by nateyoder** [comment]
Can anyone confirm if this has also been fixed with a redis backend as well like the original poster described?  As far as I could tell the Kombu PR didn't seem to contain any redis changes?

**Comment by davidt99** [comment]
This is still reproducible on celery 4.4.0rc3. From the conversation, it doesn't state which commit closed it. celery/kombu#926 doesn't seem related.

**Comment by auvipy** [comment]
thanks for your report david

**Comment by dipAch** [comment]
@davidt99 Do you have the results backend configured? If yes, what does the task state in  the result store say? Just enquiring to check the behaviour for one of my use-cases.

**Comment by davidt99** [comment]
The celery output:
```
  -------------- celery@c7c755a0cc2d v4.3.0 (rhubarb)
 ---- **** ----- 
 --- * ***  * -- Linux-4.15.0-70-generic-x86_64-with-debian-9.6 2019-11-19 08:24:35
 -- * - **** --- 
 - ** ---------- [config]
 - ** ---------- .> app:         foo:0x7f8e15f7fba8
 - ** ---------- .> transport:   redis://foo_redis:6379/1
 - ** ---------- .> results:     redis://foo_redis:6379/1
 - *** --- * --- .> concurrency: 4 (prefork)
 -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
 --- ***** ----- 
  -------------- [queues]
                 .> celery-foo exchange=celery-foo(direct) key=celery-foo
```

We have `task_acks_late` and `task_track_started` turned on.

**Comment by dipAch** [comment]
Not able to reproduce this issue on celery version `v4.4.0rc4 (cliffs)`. I have `task_acks_late` and `task_track_started` turned on as well. Task gets successfully acked before exit (on warm shutdown).

- Task state in Redis:

```
127.0.0.1:6379[1]> GET "celery-task-meta-412fa999-b591-405c-b2b0-87681d2038f8"
"{\"status\": \"SUCCESS\", \"date_done\": \"2019-12-06T05:43:29.590482\", \"task_id\": \"412fa999-b591-405c-b2b0-87681d2038f8\", \"traceback\": null, \"result\": 215, \"children\": []}"
```

- Project report:

```
software -> celery:4.4.0rc4 (cliffs) kombu:4.6.5 py:2.7.17
            billiard:3.6.1.0 redis:3.3.11
platform -> system:Linux arch:64bit
            kernel version:4.9.184-linuxkit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/1

broker_url: u'redis://redis:6379/0'
include: ['tasks']
result_backend: u'redis://redis:6379/1'
```

**Comment by freedrikp** [comment]
I can reproduce this on 4.4.2 but only if I use a RabbitMQ broker. If I use a Redis broker it works as expected.

```
software -> celery:4.4.2 (cliffs) kombu:4.6.8 py:3.6.12
            billiard:3.6.3.0 redis:3.4.1
platform -> system:Linux arch:64bit, ELF
            kernel version:4.15.0-65-generic imp:CPython

task_acks_late: True
task_acks_on_failure_or_timeout: True
task_publish_retry: False
task_reject_on_worker_lost: False
task_track_started: True
```

**Comment by freedrikp** [comment]
Can reproduce with Celery 5.0.4 as well:

```
software -> celery:5.0.4 (singularity) kombu:5.0.2 py:3.6.12
            billiard:3.6.3.0 py-amqp:5.0.2
```

**Comment by supreme-core** [comment]
Is this issue resolved for celery 5.3.1 ???

**Comment by Laza034** [comment]
Hi, we are experiencing this issue with rabbitMQ still.
Any progress on this being solved and working as expected?
Celery version: `5.3.0 (emerald-rush)`

RabbitMQ message:

`rabbitmq-0 2023-12-14 16:08:51.546499+00:00 [error] <0.2718.21> closing AMQP connection <0.2718.21> (100.64.4.74:518 │
│ 06 -> 100.64.19.213:5672):                                                                                           │
│ rabbitmq-0 2023-12-14 16:08:51.546499+00:00 [error] <0.2718.21> missed heartbeats from client, timeout: 60s`

We have some long running tasks and shutdown does not happen as fast as we would like so i guess it goes over 60s timeout and sees a lost connection with rabbitmq. As usual message stayed unacked which is not acceptable in our case. Ofc we are using late_ack.

**Comment by jarshwah** [comment]
This is still an issue, but I've tracked down the cause and a workaround. You can replicate it yourself using this [test-bed](https://github.com/jarshwah/experiments-celery).

The problem exists because of [application heartbeats](https://docs.celeryq.dev/en/latest/userguide/configuration.html#broker-heartbeat). During a warm shutdown, if tasks finish relatively quickly, they'll correctly send an ACK when `acks_late=True` is configured. But if a task takes longer than the expected application heartbeat, rabbitmq will detect the missing heartbeat, drop the connection, and return the tasks on that connection back to the queue ready to be redelivered.

When `broker_heartbeat=120` and `broker_heartbeat_checkrate=2` (the default), the disconnection will be detected after 60 seconds, which is why folks are only seeing the problematic behaviour for tasks that take longer than 1 minute to execute.

The workaround is to completely disable application heartbeats with `broker_heartbeat=None`. I believe `without-heartbeat` is irrelevant here, as it has to do with the event system and isn't used for ampq application heartbeats. You'll also want to ensure that TCP keepalives are configured correctly, which most cloud vendors do for you, and they even recommend setting `broker_heartbeat=None` to avoid these kinds of problems.

A real fix would be to send application heartbeats even during a warm shutdown. That way RMQ won't drop the connection while celery is still doing work.

**Comment by ivanprjcts** [comment]
> This is still an issue, but I've tracked down the cause and a workaround. You can replicate it yourself using this [test-bed](https://github.com/jarshwah/experiments-celery).
> 
> The problem exists because of [application heartbeats](https://docs.celeryq.dev/en/latest/userguide/configuration.html#broker-heartbeat). During a warm shutdown, if tasks finish relatively quickly, they'll correctly send an ACK when `acks_late=True` is configured. But if a task takes longer than the expected application heartbeat, rabbitmq will detect the missing heartbeat, drop the connection, and return the tasks on that connection back to the queue ready to be redelivered.
> 
> When `broker_heartbeat=120` and `broker_heartbeat_checkrate=2` (the default), the disconnection will be detected after 60 seconds, which is why folks are only seeing the problematic behaviour for tasks that take longer than 1 minute to execute.
> 
> The workaround is to completely disable application heartbeats with `broker_heartbeat=None`. I believe `without-heartbeat` is irrelevant here, as it has to do with the event system and isn't used for ampq application heartbeats. You'll also want to ensure that TCP keepalives are configured correctly, which most cloud vendors do for you, and they even recommend setting `broker_heartbeat=None` to avoid these kinds of problems.
> 
> A real fix would be to send application heartbeats even during a warm shutdown. That way RMQ won't drop the connection while celery is still doing work.

Thank you @jarshwah I could confirm that the issue is related to the healthcheck functionality. I am using `acks_late=True` and executing long-running tasks on a celery worker.

When I warm shutdown the worker, message state is changed from `Unacked` to `Ready` (rabbitMQ). After setting `broker_heartbeat=None` the issue was fixed.
