### ISSUE TITLE
Celery 4.2.0 - 5.6.0: Exception in group nested in double chain is raising internal error

### ISSUE THREAD

**Issue by kstachniuk** [celery/celery#4834]
## Checklist
celery -A proj report

software -> celery:4.2.0 (windowlicker) kombu:4.2.0 py:3.5.2
            billiard:3.5.0.3 py-amqp:2.3.2 
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis:///

## Steps to reproduce
Create a group with failing task. Group should be nested in chain, which will be in another chain.

```
@shared_task
def my_failing_task(raise_error):
    if raise_error:
        raise Exception("Raising exception")
    return "OK my_failing_task"

@shared_task
def my_task_result(p1):
    logger.info("my_task_result: {}".format(p1))
    return "OK my_task_result"

@shared_task
def on_error_task(*args, **kwargs):
    logger.info("on_error_task: {}, {}".format(args, kwargs))
    return "OK on_error_task"

def create_nested_chain_with_group():
    group_of_tasks = group(my_failing_task.si(raise_error=False), my_failing_task.si(raise_error=True))
    return chain(group_of_tasks, my_task_result.s())

def run():
    second_chain = chain(create_nested_chain_with_group(),
                         my_task_result.s())
    second_chain.link_error(on_error_task.s("Error caught by second_chain"))
    second_chain()
```

This as expected will raise Exception('Raising exception',)

## Expected behavior
`` on_error_task `` should be run and log which task has failed

## Actual behavior
`` on_error_task `` is not runned and whole task crashes with below exception:

```
/libs/celery/app/trace.py:561: RuntimeWarning: Exception raised outside body: TypeError('sequence item 1: expected a bytes-like object, NoneType found',):
Traceback (most recent call last):
  File "/libs/celery/backends/redis.py", line 368, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/libs/celery/backends/redis.py", line 368, in <listcomp>
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/libs/celery/backends/redis.py", line 323, in _unpack_chord_result
    raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
celery.exceptions.ChordError: Dependency 3b405d80-90df-4426-8782-c8002ba3000d raised Exception('Raising exception',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/libs/celery/backends/redis.py", line 374, in on_chord_part_return
    ChordError('Callback error: {0!r}'.format(exc)),
  File "/libs/celery/backends/base.py", line 220, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/libs/celery/backends/base.py", line 227, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/libs/celery/backends/base.py", line 155, in mark_as_failure
    traceback=traceback, request=request)
  File "/libs/celery/backends/base.py", line 316, in store_result
    request=request, **kwargs)
  File "/libs/celery/backends/base.py", line 658, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/libs/celery/backends/base.py", line 564, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/libs/celery/app/trace.py", line 442, in trace_task
    uuid, retval, task_request, publish_result,
  File "/libs/celery/backends/base.py", line 146, in mark_as_done
    self.on_chord_part_return(request, state, result)
  File "/libs/celery/backends/redis.py", line 383, in on_chord_part_return
    ChordError('Join error: {0!r}'.format(exc)),
  File "/libs/celery/backends/base.py", line 220, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/libs/celery/backends/base.py", line 227, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/libs/celery/backends/base.py", line 155, in mark_as_failure
    traceback=traceback, request=request)
  File "/libs/celery/backends/base.py", line 316, in store_result
    request=request, **kwargs)
  File "/libs/celery/backends/base.py", line 658, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/libs/celery/backends/base.py", line 564, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found

  exc, exc_info.traceback)))
```

**Comment by auvipy** [comment]
@xirdneh

**Comment by xirdneh** [comment]
Sorry, didn't see this before.
Will take a look.

**Comment by aykamko** [comment]
Any updates on this? Still seeing it with 4.2.1

**Comment by xirdneh** [comment]
@aykamko
Sorry, still looking into this.

**Comment by inabhi9** [comment]
Any update on this? Seems not fixed in v4.3 too

**Comment by auvipy** [comment]
if it is not fixed in master then 4.5 or 5.0 will be

**Comment by dalmarcogd** [comment]
This error is related to callback without id, on my scenery i was using chord and a chain like callback, chain doesn't have id default. I fixed that determining a task_id to chain.

`
         chord(
                [
                    TARGET_BY_TYPE[item["type"]](item)
                    for item in message["toSend"]["items"]
                ],
            )(
                chain(
                    signature(
                        MessagesFeedbackTask,
                        args=[message],
                        priority=message_priority,
                        queue="my-queue",
                    ),
                    signature(
                        MessagesPersistTask,
                        priority=message_priority,
                        queue="my-queue",
                    ),
                    signature(
                        MessagesDynamoInsertTask,
                        priority=message_priority,
                        queue="my-queue",
                    ),
                    task_id=str(uuid4()),
                ),
            )
`

**Comment by grayguest** [comment]
try this article? https://danidee10.github.io/2019/07/09/celery-chords.html

**Comment by Alexander3** [comment]
This still happens with celery==5.2.3 and redis 6.2 as broker.
``` python
@shared_task()
def test_task(arg, *args, **kwargs):
    print(arg)
    sleep(3)
    return arg

@shared_task()
def fail():
    print("Failing task")
    sleep(1)
    raise ValueError()

def test_tasks_fail():
    chain(
        chain(group(test_task.si("g1 1"), fail.si()), test_task.si("g1 1"),).on_error(
            test_task.si("Catched exception inner chain")
        ),
        test_task.si("g1 1"),
    )()
```
Logs:
```
[2022-02-28 12:21:15,359: INFO/MainProcess] celery@alpakara-tesla ready.
[2022-02-28 12:21:24,794: INFO/MainProcess] Task apps.main.tasks.test_task[9af988d5-6fcf-450f-b6fb-6e9bd672005f] received
[2022-02-28 12:21:24,795: WARNING/ForkPoolWorker-1] g1 1
[2022-02-28 12:21:24,801: INFO/MainProcess] Task apps.main.tasks.fail[0e9c7165-7ebf-446c-a788-60e20de44edf] received
[2022-02-28 12:21:27,815: INFO/ForkPoolWorker-1] Task apps.main.tasks.test_task[9af988d5-6fcf-450f-b6fb-6e9bd672005f] succeeded in 3.0204239599988796s: 'g1 1'
[2022-02-28 12:21:27,816: WARNING/ForkPoolWorker-1] Failing task
[2022-02-28 12:21:28,821: ERROR/ForkPoolWorker-1] Chord 'd9846244-63bf-4b16-96bb-2d243bf48781' raised: ChordError('Dependency 0e9c7165-7ebf-446c-a788-60e20de44edf raised ValueError()')
Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 200, in _inner
    reraise(*exc_info)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 195, in _inner
    return f(*args, **kwargs)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bond/work/current/nadii/NadiiUI/backend/apps/main/tasks.py", line 157, in fail
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in on_chord_part_return
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in <listcomp>
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 426, in _unpack_chord_result
    raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency 0e9c7165-7ebf-446c-a788-60e20de44edf raised ValueError()
[2022-02-28 12:21:28,825: WARNING/ForkPoolWorker-1] /home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py:660: RuntimeWarning: Exception raised outside body: TypeError('sequence item 1: expected a bytes-like object, NoneType found'):
Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 200, in _inner
    reraise(*exc_info)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 195, in _inner
    return f(*args, **kwargs)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bond/work/current/nadii/NadiiUI/backend/apps/main/tasks.py", line 157, in fail
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in on_chord_part_return
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in <listcomp>
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 426, in _unpack_chord_result
    raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency 0e9c7165-7ebf-446c-a788-60e20de44edf raised ValueError()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 379, in on_error
    R = I.handle_error_state(
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 225, in handle_failure
    task.backend.mark_as_failure(
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 177, in mark_as_failure
    self.on_chord_part_return(request, state, exc)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 539, in on_chord_part_return
    return self.chord_error_from_stack(callback, exc)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 309, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 316, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, exception_info.traceback)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 172, in mark_as_failure
    self.store_result(task_id, exc, state,
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 956, in _store_result
    current_meta = self._get_task_meta_for(task_id)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 978, in _get_task_meta_for
    meta = self.get(self.get_key_for_task(task_id))
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 856, in get_key_for_task
    return key_t('').join([
TypeError: sequence item 1: expected a bytes-like object, NoneType found

  warn(RuntimeWarning(

[2022-02-28 12:21:28,827: ERROR/ForkPoolWorker-1] Task apps.main.tasks.fail[0e9c7165-7ebf-446c-a788-60e20de44edf] raised unexpected: TypeError('sequence item 1: expected a bytes-like object, NoneType found')
Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 200, in _inner
    reraise(*exc_info)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 195, in _inner
    return f(*args, **kwargs)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bond/work/current/nadii/NadiiUI/backend/apps/main/tasks.py", line 157, in fail
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in on_chord_part_return
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 520, in <listcomp>
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 426, in _unpack_chord_result
    raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency 0e9c7165-7ebf-446c-a788-60e20de44edf raised ValueError()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 379, in on_error
    R = I.handle_error_state(
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/app/trace.py", line 225, in handle_failure
    task.backend.mark_as_failure(
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 177, in mark_as_failure
    self.on_chord_part_return(request, state, exc)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/redis.py", line 539, in on_chord_part_return
    return self.chord_error_from_stack(callback, exc)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 309, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 316, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, exception_info.traceback)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 172, in mark_as_failure
    self.store_result(task_id, exc, state,
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 956, in _store_result
    current_meta = self._get_task_meta_for(task_id)
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 978, in _get_task_meta_for
    meta = self.get(self.get_key_for_task(task_id))
  File "/home/bond/.virtualenvs/backend-4I_U3jTL/lib/python3.9/site-packages/celery/backends/base.py", line 856, in get_key_for_task
    return key_t('').join([
TypeError: sequence item 1: expected a bytes-like object, NoneType found
```

**Comment by mwodonnell** [comment]
This appears to still be occurring in Python 3.11.2 and Celery 5.3

**Comment by auvipy** [comment]
> This appears to still be occurring in Python 3.11.2 and Celery 5.3

thanks for verifying

**Comment by auvipy** [comment]
we got a prospective fix for this. please try and report
