### ISSUE TITLE
celery worker not able to reach sqs

### ISSUE THREAD

**Issue by gavihs** [celery/celery#5020]
## Checklist
Name: celery
Version: 4.1.1
Summary: Distributed Task Queue.
Home-page: http://celeryproject.org
Author: Ask Solem
Author-email: ask@celeryproject.org
License: BSD
Location: /usr/local/lib/python3.5/site-packages
Requires: kombu, pytz, billiard

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [X ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
We are installing Airflow with Celery Executor
Airflow configuration is using SQS
pip-3.5 install apache-airflow
pip-3.5 install apache-airflow[s3]
pip-3.5 install apache-airflow[hive]
pip-3.5 install apache-airflow[postgres]
pip-3.5 install apache-airflow[celery]
pip-3.5 install apache-airflow['kubernetes']
pip-3.5 install psycopg2-binary
pip-3.5 install runipy
pip-3.5 install boto3

pip-3.5 install celery
pip-3.5 install celery[sqs]

## Expected behavior
Celery Worker should reach the SQS and get the information
## Actual behavior
[2018-08-30 15:41:46,519] {_internal.py:88} INFO -  * Running on http://0.0.0.0:8793/ (Press CTRL+C to quit)
[2018-08-30 15:43:58,779: CRITICAL/MainProcess] Unrecoverable error: Exception('Request Empty body  HTTP 599  Failed to connect to eu-west-1.queue.amazonaws.com port 443: Connection timed out (None)',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 207, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 316, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 592, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/http/curl.py", line 114, in on_writable
    return self._on_event(fd, _pycurl.CSELECT_OUT)
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/http/curl.py", line 124, in _on_event
    self._process_pending_requests()
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/http/curl.py", line 132, in _process_pending_requests
    self._process(curl, errno, reason)
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/http/curl.py", line 178, in _process
    buffer=buffer, effective_url=effective_url, error=error,
  File "/usr/local/lib/python3.5/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/usr/local/lib/python3.5/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/local/lib/python3.5/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.5/site-packages/vine/funtools.py", line 100, in _transback
    return callback(ret)
  File "/usr/local/lib/python3.5/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/local/lib/python3.5/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.5/site-packages/vine/funtools.py", line 98, in _transback
    callback.throw()
  File "/usr/local/lib/python3.5/site-packages/vine/funtools.py", line 96, in _transback
    ret = filter_(*args + (ret,), **kwargs)
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/aws/connection.py", line 233, in _on_list_ready
    raise self._for_status(response, response.read())
Exception: Request Empty body  HTTP 599  Failed to connect to eu-west-1.queue.amazonaws.com port 443: Connection timed out (None)

 -------------- celery@ip-10-92-19-197 v4.1.1 (latentcall)
---- **** -----

**Comment by parthu50** [comment]
Are you able to resolve this issue? I am having the same issues in my private network. please share your findings

**Comment by gavihs** [comment]
@parthu50 I was not able to resolve this and we changed course to using Redis and it works just fine. However, what I figured out is that we now have a endpoint interface for sqs - this was not available earlier

I suggest you to try creating an sqs endpoint and see if this works - this should work as we need a route to the sqs, especially in a private VPC and the end point will provide the route

**Comment by auvipy** [comment]
could you try celery 4.3rc2?

**Comment by thedrow** [comment]
This issue is fixed in Kombu 4.5.0.

**Comment by marianobrc** [comment]
I beleive this isn't fixed yet. 
I tested it using

> boto3==1.17.102
> botocore==1.20.102
> celery==5.1.2
> kombu==5.1.0


This is related to boto3 using a wrong endpoint url for sqs by default. So celery doesn't work with SQS using VPC endpoints. 

Boto3 related issue
https://github.com/boto/boto3/issues/1900

AWS states what endpoint should be used here
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-sending-messages-from-vpc.html

In the mean time, would it be possible to override the parameters used during boto3 client initialization to change the endpoint url somehow?

**Comment by marianobrc** [comment]
I found a workaround and commented it here https://github.com/boto/boto3/issues/1900 in case it helps someone else.

**Comment by goatwu1993** [comment]
I faced the same issue. Finally, I figured out how to make celery work with SQS endpoints. Below is the settings

```python

AWS_SQS_REGION = os.environ["AWS_SQS_REGION"]
AWS_SQS_NAME = os.environ["AWS_SQS_NAME"]
AWS_ACCOUNT_ID = os.environ["AWS_ACCOUNT_ID"]
AWS_SQS_URL = (
    f"https://sqs.{AWS_SQS_REGION}.amazonaws.com/{AWS_ACCOUNT_ID}/{AWS_SQS_NAME}"
)

# This force celery to connect to sqs vpc endpoint
BROKER_URL = f"sqs://@sqs.{AWS_SQS_REGION}.amazonaws.com" 
TASK_CREATE_MISSING_QUEUES = False
TASK_DEFAULT_QUEUE = "celery"
BROKER_TRANSPORT_OPTIONS = {
    "region": AWS_SQS_REGION,
    "is_secure": True, # This fix celery trying to connect to sqs endpoint with http
    "predefined_queues": {
        TASK_DEFAULT_QUEUE: {
            "url": AWS_SQS_URL,
        }
    },
}
```
Precondition
- The celery app use SQS as the broker
- The celery app has an IAM role attached
- The celery app has a security group attached, with outbound to internet blocked.
- AWS VPC, VPC endpoints for SQS (KMS optionally)

Explanation:
1. We set up an SQS VPC Endpoint `sqs.{region}.amazonaws.com`, which we want celery to connect to.
1. With `BROKER_URL="sqs://"`, celery will try to connect to `queue.{region}.amazonaws.com`. Celery will raise some urllib3 timeout error while trying to connect to `queue.{region}.amazonaws.com`.
1. After some investigation, we found out `queue.{region}.amazonaws.com` is the legacy SQS endpoint, which is on the internet and does not support VPC Endpoint
3. Kombu stated that it can specify the endpoint URL. So I update the config to be `BROKER_URL="sqs://@sqs.{region}.amazonaws.com"`
4. Timeout error disappeared, replaced by http version mismatch error. This is due to Celery trying to connect to the SQS VPC endpoint with HTTP while this endpoint support only HTTPS.
5. Turn out I have to specify `is_secure: True` in BROKER_TRANSPORT_OPTIONS to have Kombu connect to the SQS VPC Endpoint with HTTPS.

**Comment by marianobrc** [comment]
Thanks for sharing @goatwu1993. I recently faced this issue again too. In my case, I was using using `boto3==1.21.21` and `celery[sqs]==5.2.3`. I solved it just setting the queue url in the proper format in BROKER_TRANSPORT_OPTIONS. And instead of setting `is_secure` I just did set the url starting with `https`,  and that did the trick.

These are my full settings (it's from a Django project):
```
# AWS Settings
AWS_ACCOUNT_ID = os.getenv("AWS_ACCOUNT_ID")
AWS_REGION_NAME = os.getenv("AWS_REGION_NAME")
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
# Pass only json serializable arguments to tasks
CELERY_TASK_SERIALIZER = "json"
# We ignore the celery task "result" as we don't need it.
# We keep track of status and/or results in our own DB models as necessary.
CELERY_TASK_IGNORE_RESULT = True
# Celery settings for SQS when running in AWS
CELERY_BROKER_URL = "sqs://"  # Let celery get credentials from env vars or from queue settings
SQS_DEFAULT_QUEUE_URL = os.getenv("SQS_DEFAULT_QUEUE_URL")
CELERY_TASK_DEFAULT_QUEUE = SQS_DEFAULT_QUEUE_URL.split('/')[-1]  # Get the queue name
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "region": AWS_REGION_NAME,
    "visibility_timeout": 3600,
    "polling_interval": 5,
    'predefined_queues': {  # We use an SQS queue created previously with CDK
        CELERY_TASK_DEFAULT_QUEUE: {
            'url': SQS_DEFAULT_QUEUE_URL  # Important: Set the queue URL with https:// here when using VPC endpoints
        }
    }
}
```

**Comment by NikhilMJain** [comment]
Setting `"is_secure": True` worked for me.
