### ISSUE TITLE
auto retry fails when expires is set

### ISSUE THREAD

**Issue by PelegAtVia** [celery/celery#7091]
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [x] I have included the contents of ``pip freeze`` in the issue.
* [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**: 5.2.0 (dawn-chorus)

<details>
<summary><b><code>celery report</code> Output:</b></summary>

<p>

```
software -> celery:5.2.0 (dawn-chorus) kombu:5.2.1 py:3.8.6
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Darwin arch:64bit
            kernel version:18.7.0 imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None

```

</p>
</details>

# Steps to Reproduce
1. create task.py with contents:

```
@app.task(autoretry_for=(Exception,), retry_backoff=True, name="task", acks_late=True)
def task():
    print("failing")
    raise Exception()

if __name__ == '__main__':
    task.apply_async(queue='task', expires=60)
```

1. run `celery -A task worker -n task -Q task`
1. run `python task.py`

## Required Dependencies

* **Minimal Python Version**: 3.8.6
* **Minimal Celery Version**: 5.2.0
* **Minimal Kombu Version**: 5.2.1
* **Minimal Broker Version**: RabbitMQ 3.8.16
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.6
billiard==3.6.4.0
celery==5.2.0
click==8.0.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
kombu==5.2.1
prompt-toolkit==3.0.22
pytz==2021.3
redis==3.5.3
six==1.16.0
vine==5.0.0
wcwidth==0.2.5

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
@app.task(autoretry_for=(Exception,), retry_backoff=True, name="task", acks_late=True)
def task():
    print("failing")
    raise Exception()

if __name__ == '__main__':
    task.apply_async(queue='task', expires=60)
```

</p>
</details>

# Expected Behavior
the task should run and fail 3 times 

# Actual Behavior
the task runs and fails once, then the following error

```
[2021-11-14 18:47:19,555: WARNING/ForkPoolWorker-2] Task task[01e23705-69eb-4021-82fa-7653611cd15f] reject requeue=False: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/Users/pelegvia/workspace/task-manager/task.py", line 25, in task
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/task.py", line 734, in retry
    S.apply_async()
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/canvas.py", line 219, in apply_async
    return _apply(args, kwargs, **options)
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/base.py", line 741, in send_task
    if expires_s < 0:
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/Users/pelegvia/.pyenv/versions/via-algo-maps3.8.6/lib/python3.8/site-packages/celery/app/task.py", line 736, in retry
    raise Reject(exc, requeue=False)
celery.exceptions.Reject: (TypeError("'<' not supported between instances of 'str' and 'int'"), False)
```

# Notes
This does not happen on 5.1.2 only on 5.2.0

**Comment by GregorMcC** [comment]
Have confirmed this is still present in `5.2.3` and is currently blocking us from upgrading to `> 5.2.2` for the recent CVE fix.

**Comment by Achilles0509** [comment]
Yes, faced with the same issue.

**Comment by Achilles0509** [comment]
Any update on the issue?

**Comment by dpdoughe** [comment]
Perhaps
https://github.com/celery/celery/blob/744ef43c4d83e190d85c034a8e5cb4ca7b7a22e0/celery/app/base.py#L738
could more robustly be implemented as
```
 expires_s = float(str(expires))
```
?

**Comment by dpdoughe** [comment]
Note that the PR https://github.com/celery/celery/pull/7109 does not yet address the root issue which is needing to be able to deal with expires that have been serialized to strings.  We still need something similar to  ``` expires_s = float(str(expires))```

**Comment by auvipy** [comment]
> Note that the PR #7109 does not yet address the root issue which is needing to be able to deal with expires that have been serialized to strings. We still need something similar to ` expires_s = float(str(expires))`

can you put some effort towards that?

**Comment by Achilles0509** [comment]
It's really critical bug.
I'm not sure why celery team doesn't check the issue.

**Comment by thedrow** [comment]
@Achilles0509 Because we lack the time? Contributions are always welcome.

**Comment by dobosevych** [comment]
The issue is in datetime serialization in kombu https://github.com/celery/kombu/blob/ea11a0b787dac7bbb35e9dc2fcb1411dd924604e/kombu/utils/json.py#L51
datetime is serialized to string that why we would have 'expires': '2022-04-11T10:00:57.215442+00:00' that is an actually a datetime to string
`expires_s = float(str(expires))`,
as a quick fix I we add `expires_s = datetime.fromisoformat(expires)`. I will create a PR with such fix.

**Comment by auvipy** [comment]
also can you check this PR as well https://github.com/celery/celery/pull/7109/files ?

**Comment by dobosevych** [comment]
> also can you check this PR as well https://github.com/celery/celery/pull/7109/files ?

This reply will actually do the same, the same maybe even better, as it will throw an error if expires can't be converted back to datetime. How can I help you with that PR?

**Comment by dobosevych** [comment]
https://github.com/celery/kombu/pull/1515 potential fix

**Comment by GustafB** [comment]
This still seems to be an issue in 5.2.6.

**Comment by auvipy** [comment]
> This still seems to be an issue in 5.2.6.

try with https://github.com/celery/kombu/pull/1515 please

**Comment by dpdoughe** [comment]
Awesome! Glad this is fixed and allowing us to move to latest releases.  

Confirmed working with: 
```
celery==5.2.7
kombu==5.2.4
flower==1.0.0
ampq==5.1.1
```

Note the work-around here for invoking flower (seems like a bug in flower though) :  
https://bytemeta.vip/repo/sontek/pyramid_celery/issues/100

**Comment by auvipy** [comment]
> I may have spoken too soon. I just didn't have long running tasks for a while. Still seeing the `TypeError: '<' not supported between instances of 'str' and 'int'` using Celery ==5.2.7. Looks like we need to wait for 5.3 according to the comments above since this fix is stated as a milestone for that release.

yes, the feature is not released yet

**Comment by kinoute** [comment]
I still have this error using Celery v5.3.0b1, pool "gevent" and concurrency at 5:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 747, in retry
    S.apply_async()
  File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 374, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 588, in apply_async
    return app.send_task(
  File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 741, in send_task
    if expires_s < 0:
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 448, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 749, in retry
    raise Reject(exc, requeue=False)
celery.exceptions.Reject: (TypeError("'<' not supported between instances of 'str' and 'int'"), False)
"""
```

Pip freeze:

```
amqp==5.1.1
billiard==4.0.2
boto3==1.24.94
botocore==1.27.94
celery==5.3.0b1
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
gevent==22.10.1
greenlet==1.1.3.post0
idna==3.4
jmespath==1.0.1
kombu==5.3.0b2
prompt-toolkit==3.0.31
python-dateutil==2.8.2
python-dotenv==0.19.2
python-magic==0.4.27
pytz==2022.5
requests==2.28.1
s3transfer==0.6.0
six==1.16.0
types-requests==2.28.9
types-urllib3==1.26.25.1
typing_extensions==4.4.0
urllib3==1.26.5
vine==5.0.0
wcwidth==0.2.5
zope.event==4.5.0
zope.interface==5.5.0
```

@app.task used:

```
@app.task(
    name='test',
    base=Test,
    bind=True,
    acks_late=True,

    autoretry_for=(
        requests.exceptions.ConnectionError,
        urllib3.exceptions.ProtocolError,
        http.client.RemoteDisconnected,
    ),
    exponential_backoff=EXPONENTIAL_BACKOFF, # 2
    retry_kwargs={'max_retries': TASK_MAX_RETRIES}, # 15
    retry_jitter=True,
)
```

**Comment by dpdoughe** [comment]
It's interesting because the kombu==5.3.0b2 in your pip freeze has the merged PR with the proposed (upstream) fix of the root cause.   https://github.com/celery/kombu/blob/6e0d26d510d9269dec33752455478baf715e311d/kombu/utils/json.py#L80

Essentially there should be no instances of str type datetime data coming back in any JSON serialized data.

**Comment by muluel** [comment]
Hi, everyone

I used shared task decorator like:
```
@shared_task(...,retry_kwargs={"max_retries":3},...)  
def task():
    ....
```
and it fails with same(TypeError < - str - int) error. When I changed with;
```
@shared_task(...,max_retries=3,...)
def task():
    ...
```
It's work for me.

Maybe this can be useful for dev. 

Celery version = 5.2.7.

Good luck.
