### ISSUE TITLE
`RuntimeError: Set changed size during iteration` with celery threads

### ISSUE THREAD

**Issue by olii** [celery/celery#7162]
In `celery` and `threads` concurrency model we run few workers with concurrency set to 20. From time to time the worker crashes with this tracelog:

```
Traceback (most recent call last):
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 311, in start
    blueprint.start(self)
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 592, in start
    c.loop(*c.loop_args())
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/clusty/clusty-prod/virtualenv/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 296, in create_loop
    for item in todo:
RuntimeError: Set changed size during iteration
```

https://github.com/celery/kombu/blob/6be95ed51f78a597a04d829df996c88f2f7bda6c/kombu/asynchronous/hub.py#L291-L298

It looks like something modifies the set. I looked where `self._ready` is used and the only plausible line is this one:
https://github.com/celery/kombu/blob/master/kombu/asynchronous/hub.py#L201

In celery `threads` model when a thread finishes a work, I believe it calls this code and adds something to the `self._ready`. When the thread is switched at the wrong time the reference to the old `self._ready` points to the old set. This may add a new item to the old set. 
I was not able to reproduce this issue nor did I try to reproduce it.

With prefork model, it doesn't cause any issue because there is only a single thread in the main process.

Here is a suggestion:
Do you think we should wrap the access to `self._ready` with a lock? A mutex that protects the access when adding a new item to the set and when swapping the object with a new one.
Let me know if you think this may be an issue.

**Comment by olii** [comment]
Finally, I got some time. The PR is in kombu.

**Comment by mvaled** [comment]
I'm seeing this issue.  My environment is:

```
CPython 3.10.2(3.10.2 (main, Jan 29 2022, 02:55:36) [GCC 10.2.1 20210110])
amqp 5.1.0
billiard 3.6.4.0
celery 5.2.3
django	4.0.3
django-celery-beat 2.2.1
django-db-geventpool  4.0.0
eventlet 0.33.0
greenlet 1.1.2
hiredis	2.0.0
kombu 5.2.4
```

I'm removing `hiredis` since I know it has caused some issues before.  However, from the code it looks like some `tick_callback()` is changing the callbacks set.

I'm using redis.  I'm getting some disconnections issues with the redis server.  The RuntimeError is possibly related but less frequent than the redis disconnection.

![Screenshot from 2022-03-23 09-55-03](https://user-images.githubusercontent.com/270825/159661194-dfb80581-1506-4f04-b261-74ac39f5f59b.png)

**Comment by auvipy** [comment]
can you try this https://github.com/celery/kombu/commit/aab2588c4ab2f8fd67c6d1c6be3243504b028504

**Comment by thedrow** [comment]
This is fixed already in celery/kombu#1489.

**Comment by claudinoac** [comment]
A similar issue is still happening in `v5.3.1`. 
There are four workers listening to the same queues in prefork mode, with high concurrency (4 to 16 processes each)
Some workers simply throw the error below and stop working.
We've been forced to restart those every few hours.

```
[2023-07-27 01:28:05,206: CRITICAL/MainProcess] Unrecoverable error: RuntimeError('Set changed size during iteration')
Traceback (most recent call last):
  File "/opt/Conversus/venv/lib/python3.8/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/opt/Conversus/venv/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/opt/Conversus/venv/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/opt/Conversus/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 336, in start
    blueprint.start(self)
  File "/opt/Conversus/venv/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/opt/Conversus/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 726, in start
    c.loop(*c.loop_args())
  File "/opt/Conversus/venv/lib/python3.8/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/opt/app/venv/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 310, in create_loop
    for tick_callback in on_tick:
RuntimeError: Set changed size during iteration
```

**Comment by a1723** [comment]
so as i understand it was fixed in [kombu v5.3.0]([v5.3.0](https://github.com/celery/kombu/releases/tag/v5.3.0)), but we still got the same error on celery v5.3.0 like [claudinoac](https://github.com/claudinoac) shows.

How can we fix this ?

**Comment by olii** [comment]
This is an issue in Kombu. I [see](https://github.com/search?q=repo%3Acelery%2Fkombu%20on_tick&type=code) that `on_tick` is used in `Redis` transport. Do you use Redis as a broker?

You will need to edit the code somehow to prevent the change of the `on_tick` during the iteration or as a workaround, use a different broker.

A systematic fix would be something like this. Although, I haven't tested it. It is my best guess. Could you run it in your environment?
```
# Create an intermediate copy of the `on_tick` that is immutable.
# The content of `on_tick` can change in callbacks.
on_tick_immutable = on_tick.copy()
for tick_callback in on_tick_immutable:
    tick_callback()
```

I can see there was a [patch](https://github.com/celery/kombu/commit/717ad3ddc98d83a7b9e2cb7054bb92a0cd6c8d53) but I can't tell if this is the issue.

**Comment by claudinoac** [comment]
@olii Thanks for the tip. 
Yes, we use Redis as broker and result backend.
I will make a fork package and run in our test environments to see what happens, but unfortunately, we've only observed this issue in production.
I've also opened a ticket with more details about our case (https://github.com/celery/celery/issues/8397)

**Comment by auvipy** [comment]
should we transfer the related new issue to kombu if that is related to kombu?

**Comment by olii** [comment]
I think we should continue in the Kombu repo.
@claudinoac you see it in production because the issue manifests itself only under the load. It is a race condition that is hard to simulate. Maybe if you create a minimal example and:
* feed a lot of dummy tasks to the worker
* introduce small delays in the code (possibly in celery internals) to increase the chance of the race condition
* inspect the kombu code more to see when the `on_tick` is modified and make that happen more often.

You can combine tips together to increase the chance of the exception in the non-prod worker.

**Comment by claudinoac** [comment]
@olii I can open a new issue in kombu once I can find the root cause by running the tests the way you're  suggesting, or even opening a PR if I ever find a fix for it.
Thanks again!

**Comment by auvipy** [comment]
i already transferred the issue in kombu
